### ISSUE TITLE
Prepare Electron pipeline

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#1]
In order to prepare for the second quarter work (Dec-Feb) on getting the desktop up and running, preparing the development, testing, build, and shipping pipeline in the time before helps us get off to a running start. We discussed this in our weekly call yesterday.

Julian is taking the lead on this, and I am excited to learn more about this pipeline as well :)

We're not going to be submitting the installers to the Windows or Mac store, due to the additional overhead. We might reconsider that for `v1.0.0` at some point, but that's down the road for now.

**Comment by juliangruber** [comment]
https://github.com/hypergraph-xyz/desktop/pull/4
