### ISSUE TITLE
Installers & uninstallers

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#11]
**Platforms**
- [x] Windows
- [x] Mac
- [x] Linux

**Specs**
- ~~User can select an install directory location (on platforms where this is standard during install)~~
- The .p2pcommons directory location is fixed
- The uninstaller does not remove any data from the .p2pcommons directory

**Comment by jameslibscie** [comment]
@juliangruber Would you consider this finished for Windows and Mac?

At what point do you think we can test these and how?

**Comment by juliangruber** [comment]
> * User can select an install directory location (on platforms where this is standard during install)

None of our installers will support this:

- Mac allows you to drag and drop the application, as usual with dmgs
- Windows will install into a default path, which is managed by the operating system
- Linux / AppImage will be for the user to move, similar to Mac

**Comment by juliangruber** [comment]
> * The .p2pcommons directory location is fixed

This doesn't have anything to do with the installers, I think we can omit this (and it is already fixed)

**Comment by juliangruber** [comment]
> * The uninstaller does not remove any data from the .p2pcommons directory

This already is the case.

**Comment by juliangruber** [comment]
I don't understand what about this issue isn't done yet, can you please expand?

**Comment by jameslibscie** [comment]
Thanks for the update @juliangruber , this seems finished to me too :)

I like to include specs / acceptance criteria that might not directly have to do with the coding of the feature at hand, as it makes clear to a tester how the feature should work.

The p2pcommons dir being fixed is a scope thing. I could imagine that someone might want to in the future choose a directory for their p2pcommons files and we might want to let them. I think I can word these kinds of specs more clearly though. (For example: it is not necessary for the user to be able to choose a directory for the p2pcommons)

What do you think?

And can we basically test these now? Should these run without errors?

**Comment by juliangruber** [comment]
> I like to include specs / acceptance criteria that might not directly have to do with the coding of the feature at hand, as it makes clear to a tester how the feature should work.

Ok yes that makes sense, I realize I was too strictly thinking about the implementation.



> The p2pcommons dir being fixed is a scope thing. I could imagine that someone might want to in the future choose a directory for their p2pcommons files and we might want to let them.

I agree very much. What about adding this to the preferences page?



> And can we basically test these now? Should these run without errors?

Yes they should. Basically there are no installers for Mac and Linux, so these can't fail. Windows I haven't tested yet.

**Comment by chartgerink** [comment]
@jameslibscie the interoperability specification right now needs it to be `~/.p2pcommons`, if we'd change that we'd need an environment variable for interoperability (e.g., `P2PCOMMONS=~/.p2pcommons`). We'd need to update the @p2pcommons/specs first in that scenario.
