### ISSUE TITLE
Expose profile name to Chatra

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#115]
_If possible in a privacy sensible manner_

- [ ] Grab the profile name and identify on Chatra with it

**Comment by juliangruber** [comment]
@chartgerink there's a method for passing arbitrary extra data to Chatra, like the user's name, email, or anything else we want really.

There's no UI in Chatra that asks the user if they want to share certain information. We _could_ open a modal or dialog for this, but that seems to disrupt when the user is already probably in an unhappy place.

What do you think?

**Comment by chartgerink** [comment]
Thanks for questioning the assumptions here 👍 

The Chatra bot now asks for name and email of the person, both optional. This is a privacy aware situation that I think is good. The auto-naming was intended to reduce friction for asking a question, but thinking again on this, it might actually increase the "am i asking an obvious question?" factor.

Given that the name on the profile is public anyway, do you think that would be privacy sensitive? I don't think this is mission critical, so whatever way we go, we can ask in tests and see. This definitely is not an identified problem as of yet.
