### ISSUE TITLE
Welcome screen / explainer

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#12]
**User story**
As a new Hypergraph user
I want to be given an introduction to the application
so that I can more quickly understand how Hypergraph works

**Workflow**
- [ ] Design
- [ ] Clickthrough
- [x] Code
- [ ] Test

**Acceptance criteria**
- Users are first greeted with a general welcome message
- Then, the *as-you-go* concept is explained briefly (in 2 screens)
- Then, the user can create their profile #13
- [DESIGN ONLY] Then, the user is prompted to subscribe to the newsletter. This is skippable
- Then, it is explained that more features (i.e., Hypergraph Vault) will be coming soon
- Then, the welcome screen can be closed
- After closing the welcome screen, the user lands on the Workspace page #18 
- The welcome screen cannot be skipped
- The welcome screen is displayed if the user does not currently have a profile
- The text should be as it is in the supplied designs

**Comment by jameslibscie** [comment]
@chartgerink We need text for the following screens:
- General welcome message when first opening the app
- Brief explanation of as-you-go
- Explanation of the *coming soon* Vault

How would you like to go about this? Do you want to write this text yourself or should I (perhaps together with @psobrakseaton) come up with a first version and run it by you? Or we could work on it together?

The same applies for issue #19, which is an explainer for what happens to your data when you add it to a content module.

**Comment by jameslibscie** [comment]
How about this?

##### Welcome message

We wish you a warm welcome to Hypergraph! 

With Hypergraph, we aim to reinvent the publication process in a way that empowers you to do better science. Science that is transparent, accessible to everyone and free from publication bias, time-consuming bureaucracy and centralised control.

Let us explain some of the basic concepts of Hypergraph before you get started...

`<Next>`

##### As-you-go publishing

You are probably used to doing research, writing a full paper and then going through the laborious process of finding a journal. At Hypergraph, we support publishing each step of your research *as-you-go*. That makes it much easier to manage your research projects and increases the value of your work by making it available to others as soon as you feel ready.

Each part of your research, whether it's a proposal, a literature study, a data set or a conclusion, is its own publication. You link them together as you go along, to create a connected body of work. This also makes it much easier to do replications or multiple studies with the same data set or underlying theory, even if someone else created it. You just link your content to the existing content and there you go!

`<Next>`

##### Create your profile

Your profile is where your published work is collected. Right now, your profile lives on your computer and is just for you. In later versions of Hypergraph, your profile and the content associated with that profile can be shared with others and made accessible to the general public, if you wish to do so.

`<Next>`

##### We don't need your e-mail

But we'd like it! We're hoping your into the Hypergraph concept and our (really cool and open) organisation, *Liberate Science*. If you want to stay up-to-date with all our goings-on or get involved in our community, drop your e-mail address here! We greatly appreciate it.

<Data agreement>

`<Next>`

##### Hypergraph Vault *(possibly merge with create profile?)*

Coming soon! This is where all research published using Hypergraph can be registered and stored to make it publicly and permanently available.

`<Get started!>`

**Comment by psobrakseaton** [comment]
> How would you like to go about this? Do you want to write this text yourself or should I (perhaps together with @psobrakseaton) come up with a first version and run it by you? Or we could work on it together?

I think this is a good idea. I'll take your initial version and and go through it. We can shoot it over to you, @chartgerink, for final approval when we have a version we both like.

**Comment by psobrakseaton** [comment]
> ##### Welcome message
> 
> We wish you a warm welcome to Hypergraph!

I think this is perhaps a bit _too_ friendly. Maybe simply "Welcome to Hypergraph"?

> With Hypergraph, we aim to reinvent the publication process in a way that empowers you to do better science. Science that is transparent, accessible to everyone and free from publication bias, time-consuming bureaucracy and centralised control.

I like this paragraph. Also I was just thinking, are we going with American English or UK English spelling for our official copy? I think it's probably obvious which one I am partial to haha

What are your thoughts, @chartgerink?

> ##### As-you-go publishing
> 
> You are probably used to doing research, writing a full paper and then going through the laborious process of finding a journal. At Hypergraph, we support publishing each step of your research _as-you-go_. That makes it much easier to manage your research projects and increases the value of your work by making it available to others as soon as you feel ready.
> 
> Each part of your research, whether it's a proposal, a literature study, a data set or a conclusion, is its own publication. You link them together as you go along, to create a connected body of work. This also makes it much easier to do replications or multiple studies with the same data set or underlying theory, even if someone else created it. You just link your content to the existing content and there you go!
> 
> `<Next>`

This is also quite strong in my opinion, there are a few things I am going to change in my rewrite however.

Perhaps instead of such a lengthy explanation in the welcome modal we should link out to an expansive section with explanations and examples of as-you-go research methodologies. 

I think if we want people to read the welcome modals and get any sort of primer at all we are going to need to make them much much smaller so people don't just skip ahead.

> ##### Create your profile
> 
> Your profile is where your published work is collected. Right now, your profile lives on your computer and is just for you. In later versions of Hypergraph, your profile and the content associated with that profile can be shared with others and made accessible to the general public, if you wish to do so.
> 
> `<Next>`

This is the perfect amount of information and length IMO.

> ##### We don't need your e-mail
> 
> But we'd like it! We're hoping your into the Hypergraph concept and our (really cool and open) organisation, _Liberate Science_. If you want to stay up-to-date with all our goings-on or get involved in our community, drop your e-mail address here! We greatly appreciate it.
> 
> `<Next>`

Like with the first critique, perhaps this is a tiny bit too friendly?

> ##### Hypergraph Vault _(possibly merge with create profile?)_
> 
> Coming soon! This is where all research published using Hypergraph can be registered and stored to make it publicly and permanently available.
> 
> `<Get started!>`

I like this as well. I don't think we should merge it, but I think I should have a little illustration or something to have some more substance to the announcement. I'll have to think it over.

**Comment by chartgerink** [comment]
Thanks @jameslibscie for getting us started! This is a good beginning; two general remarks I noted while reading through this is (1) we have the difficult task of not making it science specific (Hypergraph is a General Purpose Tool) and (2) finding our voice. Maybe this is my preference, but I'd enjoy us as playful and emoji's are fair game.

> ##### Welcome message
> 
> We wish you a warm welcome to Hypergraph!
> 
> With Hypergraph, we aim to reinvent the publication process in a way that empowers you to do better science. Science that is transparent, accessible to everyone and free from publication bias, time-consuming bureaucracy and centralised control.
> 
> Let us explain some of the basic concepts of Hypergraph before you get started...

Could we make this more "everyday life of the person" specific? Something like "You've taken the first step in making your work easily tracable. Hypergraph takes the load off you and helps you manage your projects with minimal attention".  I don't really like the word tracable though.

> `<Next>`
> ##### As-you-go publishing
> 
> You are probably used to writing reports research, writing a full paper and then going through the laborious process of finding a journal. At Hypergraph, we support publishing each step of your research _as-you-go_. That makes it much easier to manage your research projects and increases the value of your work by making it available to others as soon as you feel ready.
> 
> Each part of your research, whether it's a proposal, a literature study, a data set or a conclusion, is its own publication. You link them together as you go along, to create a connected body of work. This also makes it much easier to do replications or multiple studies with the same data set or underlying theory, even if someone else created it. You just link your content to the existing content and there you go!

This is very science specific (and lengthy). Something along the lines of "You might be used to writing most of your reports at the end of a project. Hypergraph helps you write tiny reports about the milestones in your project, so that you can easily compile them at the end. Plus, it helps you see how your work progressed over time."

> ##### Create your profile
> 
> Your profile is where your published work is collected. Right now, your profile lives on your computer and is just for you. In later versions of Hypergraph, your profile and the content associated with that profile can be shared with others and made accessible to the general public, if you wish to do so.

I like the screen Patch made where it read "What should we call you?" A description could be "We want you to get credit for the work you do! Whatever name you choose, you can adjust it later and it will immediately update across all your content. No more names from bygone times in your life 👋 " 

Note this has a lot of depth to it, especially for people who change their names over their life due to gender transitioning, getting married or divorced, or for whatever other reasons. This is something I'm particularly proud of about our system, as someone who changed their surname at a time in my life.

> ##### We don't need your e-mail
> 
> But we'd like it! We're hoping your into the Hypergraph concept and our (really cool and open) organisation, _Liberate Science_. If you want to stay up-to-date with all our goings-on or get involved in our community, drop your e-mail address here! We greatly appreciate it.

I think I agree with @psobrakseaton that we can tone it down a bit. Open the door, and let people walk in if they want. Proposing a bit alterantive formulation: "Excited about improving your project management? We can send you tips, tricks, new features, and more if you drop your e-mail below 📫 " I don't think we need to mention libscie.

> ##### Hypergraph Vault _(possibly merge with create profile?)_
> 
> Coming soon! This is where all research published using Hypergraph can be registered and stored to make it publicly and permanently available.
> 
> `<Get started!>`

I think this works reasonably, except that registered pops up again and it doesn't really make it clear why this matters. Note that we should hold off a bit on the permanence given that we have not made any plans yet so don't want to oversell.

Alternate formulation: "We'll be launching this soon! Consider this our hosting service, to make sure your content stays available to everyone. Pay once and you're set. No subscriptions 🎉"

**Comment by jameslibscie** [comment]
To be honest I feel like we're underselling our product if we make it non-science specific at this stage. The more general text feels much less appealing to me and a lot more vague. I think researchers have specific needs and will therefore want to feel like they are using a tool specifically made for science.

Given that our vision is to improve science and our marketing strategies will focus on science, I think we have little to lose and a lot to gain by also gearing the copy in that direction. I see the science tool vs general tool as a potential pivot to make later on, where we start science-focused and perhaps identify other opportunities that we can then also target specifically or with a more general approach.

Perhaps we can ask users at some point whether they will be using Hypergraph for science or for other projects, in order to gather data that might inform a pivot decision. We could even display different welcome text depending on that choice.

I think this is something we need to discuss more, though. I'll start off the discussion in #product on Slack and see how that goes :) Perhaps we can call Tuesday.

**Comment by jameslibscie** [comment]
So I've discussed this with @chartgerink on the phone and we agree that it's likely more effective to optimise for science for the time being, without ruling other applications out in the long run.

Regarding the profile, I feel like the name change thing is too specific and will seem irrelevant to too many people, but meaningful for some. I think just mentioning that you can change your name in small text is enough. The people who understand how much that means probably don't need it stressing :)

I also like mentioning Liberate Science because it helps with the movement-building aspect for now. I can imagine dropping it later, once we're further down the line.

Here's my latest iteration. Curious for your opinions @psobrakseaton @chartgerink 

##### Welcome message

We wish you a warm welcome to Hypergraph! 

With Hypergraph, we aim to reinvent the publication process in a way that empowers you to do better science. Science that is transparent, accessible to everyone and free from publication bias, time-consuming bureaucracy and centralized control.

Let us explain some of the basic concepts of Hypergraph before you get started...

`<Next>`

##### As-you-go publishing

You are probably used to doing research, writing a full paper and then going through the laborious process of finding a journal. At Hypergraph, we support publishing each step of your research *as-you-go*. That makes it much easier to manage your research projects and increases the value of your work by making it available to others as soon as you feel ready.

`<Learn more...>`

Each part of your research, whether it's a proposal, a literature study, a data set or a conclusion, is its own publication. You link them together as you go along, to create a connected body of work. This also makes it much easier to do replications or multiple studies with the same data set or underlying theory, even if someone else created it. You just link your content to the existing content and there you go!

`<Next>`

##### What should we call you?

It's time to create a profile! This is where your published work is collected. Right now, your profile lives on your computer and is just for you. In later versions of Hypergraph, your profile and the content associated with that profile can be shared with others and made accessible to the general public, if you wish to do so.

<sup>You can change your name later by the way 👋</sup>

`<Next>`

##### We don't need your e-mail

But we'd like it! We hope you're into the Hypergraph concept and our organisation, [*Liberate Science*](https://libscie.org/). If you want to stay up-to-date with our activities or get involved in our community, drop your e-mail address here! 📫 We greatly appreciate it.

<Data agreement>

`<Next>`

##### Hypergraph Vault

We'll be launching this soon! Consider this our hosting service, to make sure your content stays available to everyone. Pay once and you're set. No subscriptions 🎉

`<Get started!>`

**Comment by jameslibscie** [comment]
I've put this preliminary text into the application, which you can see here: https://www.figma.com/proto/CN2zNBRy25J9DCJkvv9WLc/Hypergraph-Desktop?node-id=653%3A0&viewport=587%2C593%2C0.2060069888830185&scaling=scale-down

This was really interesting, as there is much less space than I expected and some text seems very awkward. Gives a new perspective. I've had to cut quite a bit of text as well.

Curious for your input now that it can be seen "live in action"

**Comment by psobrakseaton** [comment]
I’ll take a look at this in the morning. If it’s too awkward I can always up the space of the modals. Right now it’s at an “ideal” size for design, but I can adjust it if I must.

**Comment by chartgerink** [comment]
I'm going to check this out when I do a first internal dogfood session, I think what @jameslibscie mentions, about having little space in context, is probably the biggest thing. I appreciate getting feedback from people and not us over-engineering these texts.

**Comment by juliangruber** [comment]
A design revision needs to be done

**Comment by psobrakseaton** [comment]
Currently working on a revision. We should have a quick review tomorrow morning (March 3rd) so we can implement quickly.

**Comment by jameslibscie** [comment]
Based on first internal clickthroughs, I have some small (suggestions for) adjustments to the designs. Normally I wouldn't like to change the specs once coding has started (unless absolutely necessary), but we want to be able to iterate on the clickthroughs.

- Text improvements
  - As you go:
    - Research is hard work. You're probably used to writing a full paper at the end of your research and then going through the laborious process of finding a journal, hopefully without rejections and rewrites. At Hypergraph, we support publishing each step of your research as-you-go.
    - This allows you to push through your research step by step. The value of your work increases by making it more complete and immediately available to others as soon as you feel ready. And it's written in the way you feel best fits your research, with no formats or limitations to adhere to.
    - 2nd page stays the same for now - updates will follow
  - Vault:
    - We'll be launching this soon! Consider this our hosting service, to make sure your content stays available to everyone. No paywalls, no subscriptions. Just a small, one-time hosting fee and you're set 🎉
- Remove "learn more" button from "as you go" page
- Change first "Create profile" button to "Next"
- Add progress / step counter

**Comment by juliangruber** [comment]
@jameslibscie code for the current state of designs is done

**Comment by jameslibscie** [comment]
> @jameslibscie code for the current state of designs is done

Looks great! And create profile (#13) also seems to work :)

I'm guessing that the newsletter subscribe thing is just a placeholder for now? I think you can comment out that bit and we'll make it functional in `v0.2.0`. It was only a part of the design spec.

Let me know and then we can close this one :)

**Comment by juliangruber** [comment]
> I'm guessing that the newsletter subscribe thing is just a placeholder for now? I think you can comment out that bit and we'll make it functional in `v0.2.0`. It was only a part of the design spec.

Right, didn't see this was design only. I'll remove it.

**Comment by jameslibscie** [comment]
Perfect!
