### ISSUE TITLE
Add to profile/Save as draft Buttons

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/desktop#124]
The Figma files can be found [here](https://www.figma.com/file/K3LWtNFIgEryrldIbAqIVU/%CE%B2-add-content-buttons?node-id=0%3A1).

The "Add to profile"/"Save as draft" buttons should meet the following criteria:

- [x] On the add-content screen.
- [x] The cancel action is no longer a button but a link with standard link behavior except the underline is libscie-red.
- [x] "Cancel" returns the user to the last place they where before adding content.
- [ ] "Add to profile" takes you to the Profile feed
- [ ] "Save as draft" takes you to the Drafts feed

**Comment by psobrakseaton** [comment]
Here is the link to the Figma file for this issue: [https://www.figma.com/file/K3LWtNFIgEryrldIbAqIVU/%CE%B2-add-content-buttons?node-id=143%3A798](https://www.figma.com/file/K3LWtNFIgEryrldIbAqIVU/%CE%B2-add-content-buttons?node-id=143%3A798)

In my original issue that I opened, I say that Adding to profile and Saving to drag should output to the feed with the item on top. Do you still think this is best, or would you have it output to the item itself? @chartgerink should way in on this too.

My thoughts are that it is more conventional to go to the item you just created where you can see it in its entirety, but I feel like it might not be as obvious where the item is going.

**Comment by chartgerink** [comment]
With "Add to profile" and "Save to drafts", it might be good to show the related screen that it's save to?

**Comment by juliangruber** [comment]
We don't have sorting for these screens yet so we can't ensure it's on top. For now I'd vote to navigate to the content itself.

One way to think about this might be to ask about next actions. What would you do next on the content screen? What would you do on the content list?

**Comment by psobrakseaton** [comment]
I second the vote to navigate to the content itself (especially since we have the global add content button). 

I also like the idea of asking about next actions, but I think that will have to come later. For now lets navigate to content.

**Comment by jameslibscie** [comment]
I agree that it's nice to show where the content has landed, but until we have sorting properly implemented, that could be confusing. Nothing wrong with landing on the content page imo.
