### ISSUE TITLE
Set up GitHub Sponsors

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#128]

**Comment by chartgerink** [comment]
I put our org on the waitlist :)

**Comment by chartgerink** [comment]
Done! Find our sponsor pages for each org separately

[p2pcommons](https://github.com/sponsors/p2pcommons)
[hypergraph-xyz](https://github.com/sponsors/hypergraph-xyz)
[libscie](https://github.com/sponsors/libscie)
