### ISSUE TITLE
Create profile

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#13]
**User story**
As a new Hypergraph user
I want to create a profile for myself
so that I have an identity on the Hypergraph platform and a central place to find my published work

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- Only users currently without a profile can create a profile
- The profile creator asks for the user's full name (required)
- The created profile is stored locally
- After creating a profile, the welcome screen no longer appears when opening Hypergraph
- If an error is thrown during creation, the user is shown a descriptive error and prompted to submit a bug report via e-mail

**Comment by jameslibscie** [comment]
@juliangruber This already works somewhat, but I'm getting errors on the CLI if the profile was created by Desktop. Is this expected behaviour at this point? If not, I can file bug reports.

**Comment by juliangruber** [comment]
The SDK versions of both currently are not compatible...willfix

**Comment by juliangruber** [comment]
> @juliangruber This already works somewhat, but I'm getting errors on the CLI if the profile was created by Desktop. Is this expected behaviour at this point? If not, I can file bug reports.

This has been fixed, they used two different versions. Latest master should work

**Comment by jameslibscie** [comment]
Error handling will be split off into separate issue, so this can be closed
