### ISSUE TITLE
View profile

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#14]
**User story**
As a Hypergraph user
I want to view my profile
so that I can get an overview of my published work

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- The profile page has a placeholder for an avatar in hex-shape
- The profile page displays the name and description (if a description exists - right now there is no way to do so from Desktop)
- If there are no published content modules, the profile page displays a message (in place of the "That's all of [profile name]'s content" and using the same style): "No content yet... 🤔"
- The profile page displays a list of published content modules

**Design**

<img width="1417" alt="Screenshot 2020-02-27 at 09 53 23" src="https://user-images.githubusercontent.com/10247/75427571-0d5d7480-5947-11ea-8668-3f996b3835ce.png">

**edit** by @juliangruber: add design

**Comment by juliangruber** [comment]
@jameslibscie as discussed with @psobrakseaton, I'm going to work on this issue first. Shall we move it to `step: code` then?

> * LATER: The profile page displays a list of published content modules

Why is this later? If I understand correctly, without this, no content will be displayed?

> * After a user first creates their profile, they are taken to the profile page

This belongs to the issue for creating a profile, not this one

**Comment by juliangruber** [comment]
What does "LATER" mean in general? Will this be done after this issue is closed?

**Comment by juliangruber** [comment]
> @jameslibscie as discussed with @psobrakseaton, I'm going to work on this issue first. Shall we move it to `step: code` then?

Sweet, since we use labels, this issue can be in `step: clickthrough` and `step: code` at the same time :)

**Comment by jameslibscie** [comment]
@juliangruber The spec'ing is sometimes a bit weird like that because for these fundamental issues everything is very dependent on each other. The "LATER" parts presume that the issues will be worked through in the order that I listed them, because they depend on some functionality that hasn't been built yet. It's included for reference, so the designer / dev knows to "leave space" for it.

One thing I didn't take into account, is that Desktop dev can happen using existing p2pcommons data created by the CLI. This completely changes the logical order for working on these issues, which then also means some of the specs would be better off being moved and some of the "LATER" comments no longer make sense. Right now, *create* would always have to precede *view*, when with existing data it's probably the other way round.

How would you like me to handle this? Should I take another look at the ordering and move the specs around in a way that makes sense given the fact that we already have data?

**Comment by juliangruber** [comment]
> One thing I didn't take into account, is that Desktop dev can happen using existing p2pcommons data created by the CLI.

Not only that, it can also happen using dummy data that is encoded right in the templates

**Comment by juliangruber** [comment]
I would suggest to include all specs for a release/milestone/version that we're targeting. Then we'll have as many issues in progress as necessary, until we can test them in collaboration.

Otherwise you'd have to reopen this issue once another screen becomes available, these dependencies I can just track myself implicitly

**Comment by juliangruber** [comment]
What I'm thinking about instead is which order makes sense for testing. Should I for example include all of the links in the sidebar already? Probably not, as that just confuses testing.

Should I however include the "edit profile" button, before that feature is implemented? Potentially!

**Comment by jameslibscie** [comment]
As far as I'm concerned, it's fine to include placeholders along the way if that makes your work easier and if the functionality in question will be realised later for this milestone. I think we should leave things like "Edit profile" buttons out for now, since that is part of a later milestone. We can gather feedback on these things if necessary through the mock-ups, which already implement more "future" stuff.

Let's say that by the end of each milestone, there shouldn't be any placeholders other than those that exist by way of announcement (such as an advertisement for the vault). Does that make sense to you?

**Comment by jameslibscie** [comment]
Oh and I will get to work on the specs later today :)

**Comment by jameslibscie** [comment]
@juliangruber I've gone through and updated the issues. Let me know if you think there's a mistake anywhere or disagree with a choice I've made :)

**Comment by juliangruber** [comment]
> * If there are no published content modules, the profile page displays a message that there is no content yet and encourages users to create some

This isn't designed yet

**Comment by jameslibscie** [comment]
> > * If there are no published content modules, the profile page displays a message that there is no content yet and encourages users to create some
> 
> This isn't designed yet

Correct. I've updated the spec to this:

> If there are no published content modules, the profile page displays a message (in place of the "That's all of [profile name]'s content" and using the same style): "No content yet... 🤔"

We will sort out the "encouraging" part with the tutorial that will come later.

**Comment by juliangruber** [comment]
that works :)

<img width="1071" alt="Screenshot 2020-03-03 at 11 44 33" src="https://user-images.githubusercontent.com/10247/75768347-7298d780-5d44-11ea-871e-d0ee05cb8810.png">

**Comment by jameslibscie** [comment]
Based on first internal clickthroughs, I have some small (suggestions for) adjustments to the designs. Normally I wouldn't like to change the specs once coding has started (unless absolutely necessary), but we want to be able to iterate on the clickthroughs.

- Remove "Add content" button as it may be confusing as to whether it will also immediately publish the content or not (i.e., it may work the same or differently than the button on the Home/Workspace page). We can then see in the tests whether people are missing it.
