### ISSUE TITLE
Inconsistent breadcrumbs

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#144]
## Description

When content is viewed through the profile page, it has a breadcrumb `/<name>/<content>`. When content is viewed through the Drafts screen, the breadcrumb does not show I came from the Drafts page. It might be helpful for this to be consistent across screens?

## Screenshots

![image](https://user-images.githubusercontent.com/2946344/87669224-e543a600-c76d-11ea-8eea-0a259b50bf88.png)
![image](https://user-images.githubusercontent.com/2946344/87669250-f42a5880-c76d-11ea-92a4-9c672640466c.png)

## Additional context

I know discussions surrounding the breadcrumb are being had, so please close if this is not relevant. I felt like async posting was the best way to go for now and not let it slip off the radar.

**Comment by juliangruber** [comment]
This header is not to be seen as a breadcrumb navigation, but more a single layer of hierarchy (who has registered this). It's less about authors and more about registration.

There also is another problem with this header: If multiple people registered a module, which name to show on top? Say you go to Chris's profile and click on a module, it could show Chris on top. But what if you open the content module via a link, who should we show then?

**Comment by chartgerink** [comment]
Multiple people registering a module will be difficult to show indeed. Worth talking about more (remember it coming up in the chat) but will close this for now :)
