### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#15]
**User story**
As a Hypergraph user
I want to navigate between various areas of the application using a menu
so that I can easily and quickly reach all Hypergraph features

**Workflow**
- [x] Design
- [ ] Clickthrough
- [x] Code
- [ ] Test

**Acceptance criteria**
- The menu initially has two items:
    - Workspace #18
    - Profile #14
    - [DESIGN ONLY] Feedback
    - [DESIGN ONLY] About
    - [DESIGN ONLY] Vault

**Comment by juliangruber** [comment]
@jameslibscie code is done, I think we're missing a test label here

**Comment by jameslibscie** [comment]
@juliangruber (Even) if we're not working with PRs, I think it can remain on `code` + `in progress` until it's tested, as it will usually either be verified quickly or go back and forth a few times. Does that work for you?

**Comment by juliangruber** [comment]
Let's try that 👌 So we're gonna remove the test label everywhere then, right?
