### ISSUE TITLE
Retest private key export when @p2pcommons/sdk-js upgrades

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#154]
Based on the discussion in #147 it's clear that the backup of Hypergraph currently includes the private keys, but upon merge of https://github.com/p2pcommons/sdk-js/pull/160 it might change. 

Posting this issue to keep it on our radar, unblocked when https://github.com/p2pcommons/sdk-js/pull/160 gets merged.

**Comment by juliangruber** [comment]
lost these?

![](https://media3.giphy.com/media/wS4ZMstacTdbq/giphy.gif?cid=ecf05e47ij1lvsbbal051mfvwpda8cxjzqr0i86c2h3hqaqq&rid=giphy.gif)

**Comment by jameslibscie** [comment]
Closed as https://github.com/p2pcommons/sdk-js/pull/160 won't get merged
