### ISSUE TITLE
Add content

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#16]
**User story**
As a Hypergraph user
I want to add content to Hypergraph
so that I can manage my ongoing and new projects

**Workflow**
- [ ] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- When adding a new content module, the user specifies the following in this order:
    - The content type (`subtype`), which can be chosen from a pre-defined list (same as CLI) or specified via a [Wikidata identifier](https://www.wikidata.org/wiki/Wikidata:Identifiers)
    - File(s) (at least one) to add to the content module
    - If multiple files are specified, which file is the `main` file
    - Parent module (just one, support for multiple parent modules will be added later)
    - Title
    - Description (optional)
    - Agreement to use CC0 licence
- After adding a new content module, the user is taken to a page for viewing the content #17 
- Files that are added should be copied (not moved) to the newly created dat archive
- After creating the module, it should be validated. If deemed invalid, the user is shown a descriptive error and prompted to submit a bug report via e-mail.

**Comment by jameslibscie** [comment]
Based on first internal clickthroughs, I have some small (suggestions for) adjustments to the designs.

- Form less "heavy" on the purple
- Change CC0 text to:
  - License agreement: Others may freely build upon, enhance and reuse this work for any purposes without restriction under copyright or database law. I hereby confirm that I own this work and wish for it to be accompanied by a [CC0 license](https://creativecommons.org/share-your-work/public-domain/cc0/).

**Comment by juliangruber** [comment]
> * Parent module

A module can have multiple parents

**Comment by juliangruber** [comment]
If you hit cancel on this page, or navigate away in any other way, should we let the user confirm that their changes will get lost? and shall we ask them only if they have already entered data?

**Comment by jameslibscie** [comment]
> > * Parent module
> 
> A module can have multiple parents. Spec and then design need to be updated.

This is a known issue. Having multiple parents can be added further down the line as far as I'm concerned. Having support for 1 parent is easier than support for n parents and is enough to demonstrate the concept, so I'd definitely prefer to have this included for the demo version. Should have made this clearer in the spec.


> If you hit cancel on this page, or navigate away in any other way, should we let the user confirm that their changes will get lost? and shall we ask them only if they have already entered data?

Eventually, yes. This is currently on the roadmap for a later version.

**Comment by juliangruber** [comment]
> This is a known issue. Having multiple parents can be added further down the line as far as I'm concerned. Having support for 1 parent is easier than support for n parents and is enough to demonstrate the concept, so I'd definitely prefer to have this included for the demo version. Should have made this clearer in the spec.

As discussed, I'm going to implement the 2 strategies for this, while Patch is working on designs and maybe comes up with something different.

> Eventually, yes. This is currently on the roadmap for a later version.

Ok, great that this is on the roadmap!

I think we can close this issue then and open a new one for "Add content with parent"?

**Comment by jameslibscie** [comment]
> I think we can close this issue then and open a new one for "Add content with parent"?

Yep, let me give this and #24 a run through first and then I'll close them :)

**Comment by jameslibscie** [comment]
Great work! Have a few cosmetic things that maybe aren't solvable due to cross-platform stuff:
- [ ] The `select` dropdowns are styled a bit differently from the rest, at least on Windows. On Windows I can solve this with `padding`, `border-width`, `font-family` and `letter-spacing` properties. Does this also work on Mac? If so, it might be worth doing to make it all sync up a bit more.
- [ ] The file names for uploaded files run a bit over / up to the X icons for long file names. Is it easy to do a fade out effect here? I believe that was originally in the designs as well.
- [ ] Doesn't quite belong on this issue, but I've noticed after adding content that the (greyed-out) author name and description are quite close to each other. I think something went wrong with the spacing there. When published there's more space.
![image](https://user-images.githubusercontent.com/59870484/77174432-54133a00-6ac1-11ea-9a23-71cf9211efa8.png)
![image](https://user-images.githubusercontent.com/59870484/77174445-5a091b00-6ac1-11ea-84f4-0bf4f71f8da9.png)
![image](https://user-images.githubusercontent.com/59870484/77174455-5ecdcf00-6ac1-11ea-8273-e74e7ffa5093.png)
![image](https://user-images.githubusercontent.com/59870484/77174895-0e0aa600-6ac2-11ea-9eeb-18a1d6e41dd1.png)

Feel free to close if these aren't possible / easy cross-platform atm.

**Comment by jameslibscie** [comment]
For reference, this is how it looks without modified CSS on Windows:

![image](https://user-images.githubusercontent.com/59870484/77175492-07306300-6ac3-11ea-8fb7-9ec119f3253d.png)

**Comment by juliangruber** [comment]
@jameslibscie can we actually move this to a separate issue? Patch and me think it looks _good enough_ on mac, which is what the demo is going to be on. Also, the implementation of these form components is sort of independent of this issue, as other screens can also use them, so I think it makes sense to move out :+1:

**Comment by jameslibscie** [comment]
I would normally not be a fan of splitting these off just because they are general form components. I like to follow the idea that general components are products of specific issues, rather than general components being required to start work on specific issues. That way, each issue has some kind of direct business value and this also stimulates properly finishing each issue.

However, I completely agree that this is *good enough* for the demo, and that is a very valid reason to split off imo :) I'll create one issue for the author spacing and one for prettifying the form controls.

**Comment by jameslibscie** [comment]
Closed by splitting remaining tasks off into #47 and #48
