### ISSUE TITLE
Followed profile list

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#161]
- [x] New menubar entry
- [x] List followed profiles
- [x] Let each be unfollowed (and followed again)
- [ ] Empty list design
- [x] Hover design

[Figma](https://www.figma.com/file/PcCVjYCfHPS3OP2hlgfVnK/networking-feature-followed-profiles-list?node-id=47%3A0)

**Comment by psobrakseaton** [comment]
Design Specs:
- [ ] New main menu entry
- [ ] List of followed profiles
- [ ] Follow/Unfollow profiles
- [ ] Empty list design
- [ ] Hover state

Questions:
- [ ] Actions for unfollowing (will they immediately leave the list when unfollowed?)
- [ ] Should there be an option to copy the profile link from this list?

**Comment by jameslibscie** [comment]
Unfollow and share buttons that appear on hover would be really nice

**Comment by juliangruber** [comment]
> * Actions for unfollowing (will they immediately leave the list when unfollowed?)

I guess switching to the Follow button until the page is reloaded is a nice pattern



> * Should there be an option to copy the profile link from this list?

Let's add that when it comes up

**Comment by psobrakseaton** [comment]
The design is ready to go at the Figma link above!

@jameslibscie @chartgerink We still need copy for the empty list. I think the action of finding then following a profile is too much to be explained in the short string. I think we should stick to something like "Nothing here yet. Follow some profiles to get started! :emoji:"

**Comment by chartgerink** [comment]
> You're not following anybody yet 😅

How about this for copy? ☝️

**Comment by psobrakseaton** [comment]
> > You're not following anybody yet 😅
> 
> How about this for copy? ☝️
> 
> I will admit that the "Connect" screen makes me think this is a page where I can _find_ people to follow instead of see the ones I _am_ following. Wonder whether we could just call this "Following"?

I like both of these suggestions a lot! At some point we tried calling it "connect" and so that is the nomenclature I used, but "Following" works great.

So I see the copy requirements as being:

- [ ] For the empty list -> **You're not following anybody yet 😅**
- [ ] For the main menu button and the page header -> **Following**

**Comment by jameslibscie** [comment]
Sounds good to me!

**Comment by juliangruber** [comment]
> I will admit that the "Connect" screen makes me think this is a page where I can _find_ people to follow instead of see the ones I _am_ following. Wonder whether we could just call this "Following"?

Agreed, it's confusing because you click "Connect" but get to a screen where you don't do "connecting".

**Comment by psobrakseaton** [comment]
> > I will admit that the "Connect" screen makes me think this is a page where I can _find_ people to follow instead of see the ones I _am_ following. Wonder whether we could just call this "Following"?
> 
> Agreed, it's confusing because you click "Connect" but get to a screen where you don't do "connecting".

100%. I think "Following" is a really good way to put it for now. I have reflected that in some of the designs, but not all. Lets consider it decided from here.

**Comment by juliangruber** [comment]
@psobrakseaton what do you think about moving the "Following" link from the menu bar to the profile? Because you might also want to check out which people others are following, when looking at their profile

**Comment by juliangruber** [comment]
In respect to timing, this might be something to change after the release

**Comment by psobrakseaton** [comment]
> @psobrakseaton what do you think about moving the "Following" link from the menu bar to the profile? Because you might also want to check out which people others are following, when looking at their profile

This is definitely the place where it _should be_, but I think we should table that for now. This could be off base, but in my head I have been planning on a reorganization and navigation deep-dive in the near future after release. Around the same time we remove the back buttons and introduce breadcrumbs.
