### ISSUE TITLE
View followed content (feed)

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#165]
A feed of all content by people you follow (including yourself).

- [x] Add menubar entry
- [x] Add new feed page 
- [x] For every person you follow (and yourself), list all contents
- [x] Sort contents by timestamp
- [x] Reuse existing designs, so eg `+` button would be there

[Figma](https://www.figma.com/file/4wGmLpbNsTVSaLc6u7jkYD/View-followed-content-(feed)-%23165) | Review @jameslibscie

**Comment by psobrakseaton** [comment]
Link to Figma: [View followed content (feed) #165](https://www.figma.com/file/4wGmLpbNsTVSaLc6u7jkYD/View-followed-content-feed-165?node-id=1%3A3)

This initial version of the content feed will be very visually similar to the drafts feed, but the list will be populated by the content from the profiles you follow.

Proposed Design Specifications:
- New main menu button "Feed"
- Show published content from all followed profiles (including yourself).
- Ability to build upon the modules (The "+" should be there).

Are there any immediately obvious items missing from these design specifications, @jameslibscie @chartgerink?

**Comment by psobrakseaton** [comment]
The linked Figma has been updated to to reflect the current design. I opted for the simplest solution which required pretty much no creation of new assets. It meets the specifications we outlined here, but if there are any states or pieces missing, please let me know and I will reassign this task to myself.

@jameslibscie @chartgerink We need another bit of copy for an empty feed. Any suggestions?

**Comment by chartgerink** [comment]
> Share content or follow someone to fill up your feed :raised_hands: 

Maybe something like this? :point_up: 

Also, what is the logic for the ordering of the tabs on the left? Maybe it would be worth to do alphabetical ordering?

**Comment by psobrakseaton** [comment]
> Also, what is the logic for the ordering of the tabs on the left? Maybe it would be worth to do alphabetical ordering?

I'm really glad you brought this up! This is something that I've made a mental note about but keep forgetting to talk about. Should we come up with a provisional logic here? 

I think we can reasonably forecast what tabs we will have in the near future and we should find the best order.

Off the top I'm thinking:

- Feed
- Drafts
- Following
- Profile

**Comment by jameslibscie** [comment]
Hmm, so I'm thinking about likely scenarios. I would imagine that for a lot of users, if the feed also displays own registered content, it will only contain own registered content. Would it not make more sense, to be able to differentiate better between different features, that it only displays registered content by followed profiles? Otherwise, if you haven't followed anyone, you basically have 2 different views of your profile which could be confusing. I think it's also valuable to use the empty space to encourage users to follow people, like:
> Follow someone to fill up your feed 🙌

**Comment by jameslibscie** [comment]
So @juliangruber mentioned Twitter feeds containing own content over at #192. Is it included because other people react to your stuff? Because we don't have that for Hypergraph now and I can imagine "replies to your things" being part of your feed but purely your own content not so much.

**Comment by psobrakseaton** [comment]
@jameslibscie I think you raise some really good concerns about the redundancy of content and using the empty space to encourage networking behavior. Perhaps there is a way to display your own content in the feed and have a call-to-action up at the top if you aren't following anyone .

I think the initial, instinctual ordering of feed, drafts, following, profile, makes the most sense with common patterns and we should do that for now and then review again later as we add more features.

**Comment by juliangruber** [comment]
We can also try a feed without your own content and see if it works. Filtering it out is simple to implement.

**Comment by juliangruber** [comment]
I agree with patch though, especially for a new app we should follow known patterns as much as possible

**Comment by psobrakseaton** [comment]
> We can also try a feed without your own content and see if it works. Filtering it out is simple to implement.

That is also an option as well. Start without having your content in the feed since we don't have the same types of community interaction tools. I think this allows us to have our cake and eat it too...We still can encourage the networking behavior and we don't have to create overly complex design and development solutions just yet.

**Comment by jameslibscie** [comment]
Spoke with @chartgerink and @juliangruber about this in the dev chat and I'm on board with including own content in the feed. Having the "Follow someone to fill up your feed 🙌" message display if you have 0 remote content (even if there is own content) would be a nice touch, but not worth it if this requires extra design time.

**Comment by juliangruber** [comment]
We decided in a call that the feed would also contain your own content, to follow existing and well known patterns.

We verified this behavior can also be seeon on facebook:

![Image from iOS](https://user-images.githubusercontent.com/10247/88681967-68f87d80-d0f2-11ea-81de-71ed10c36947.jpg)
