### ISSUE TITLE
Connected/disconnected status indicator

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/desktop#168]
Figma: [Connected/disconnected status indicator - #168](https://www.figma.com/file/3iMRh8xBPrT0UU8d8W5Wh0/Connected-disconnected-status-indicator?node-id=0%3A1)

Specs:
TBD

**Comment by juliangruber** [comment]
Proposed specs:
- [ ] figure out if online
- [ ] change the icon's color:
  - [ ] green if functional
  - [ ] yellow if holepunching unavailable
  - [ ] red if not connected

**Comment by psobrakseaton** [comment]
@juliangruber Do we have the option of using a system hover for additional information? So we can having something like a singular icon but if you hover it could give you a text descriptor?

**Comment by juliangruber** [comment]
Yes, we can do that

**Comment by psobrakseaton** [comment]
Perfect. Tomorrow (if you are available) I'd love to give you a 1 minute walkthrough so if you see any problems they ca be addressed before I kick the design to you for dev.

**Comment by psobrakseaton** [comment]
Design is delivered! Have fun!
