### ISSUE TITLE
View content

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#17]
**User story**
As a Hypergraph user
I want to view my added content
so that I can access my work from within Hypergraph

**Workflow**
- [ ] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- The user can see the following:
    - Parent module (if any)
    - Title
    - Description (if any)
    - Authors (if any)
    - List of files (main first)
    - Date modified (if owned by current user)
    - Version number
- If a parent module exists, there is a way for the user to directly navigate to the content page of the parent module
- #23 adds an "Open folder" button to this page
- #24 adds a "Publish" button to this page (only if content is not already published)
- [DESIGN ONLY] There is a button for exporting the content 
- [DESIGN ONLY] There is a button for deleting the content 
- [DESIGN ONLY] There is a button for unpublishing the content that displays if the content is already published
- [DESIGN ONLY] There is a button for editing the content
- [DESIGN ONLY] There is a button for downloading files that are not already downloaded

**Comment by juliangruber** [comment]
> * [DESIGN ONLY] There is a button for exporting the content
> * [DESIGN ONLY] There is a button for deleting the content
> * [DESIGN ONLY] There is a button for unpublishing the content that displays if the content is already published

I missed this and already implemented it 🤷‍♀

**Comment by juliangruber** [comment]
> * Date modified (if owned by current user)

We don't have this in the SDK

**Comment by jameslibscie** [comment]
> > * [DESIGN ONLY] There is a button for exporting the content
> > * [DESIGN ONLY] There is a button for deleting the content
> > * [DESIGN ONLY] There is a button for unpublishing the content that displays if the content is already published
> 
> I missed this and already implemented it 🤷‍♀

No worries :) when it comes to those parts of the Roadmap, I'll create issues for further improving these if necessary.

What is the sorting in the Workspace based on btw if date modified isn't available?

**Comment by juliangruber** [comment]
> What is the sorting in the Workspace based on btw if date modified isn't available?

I don't know, it might be random

**Comment by jameslibscie** [comment]
This is also great! Just a couple of small things:

- [ ] The author name displays (as a link) even if the module isn't published. Is this according to the current designs? I haven't spec'd it either way, but it was designed differently at first. (I initially thought that the `authors` field was only filled upon publishing). I would suggest to keep the Workspace and View content pages consistent and only display the author name if the content is published. If this is confusing (i.e., people are missing the author name), we can adjust it later. 
- [ ] Clicking the author name takes me to the Workspace, rather than the author's profile page

**Comment by juliangruber** [comment]
Both implemented (although I'm still strongly against hiding authors if unpublished :P)

**Comment by jameslibscie** [comment]
Nice! Will check it out shortly. If you prefer, you can change it to something like:

Author Names (not yet published)

or 

Author Names (draft)

What's most important to me is that it's not a link to the profile and there's the visual indication of it not being published yet.

**Comment by juliangruber** [comment]
> it's not a link to the profile

This is because we currently don't list unpublished modules on the profile page, which is most likely going to change with our planned design updates.

> and there's the visual indication of it not being published yet.

This indication is already present in the colored hex. Let's use either or. Currently this hex is just noise then, as the author / no author line will tell you something is unpublished. That's not clear design.

And another downside is that you won't be able to tell who are the authors of your draft, at all. Why hide this information?

**Comment by jameslibscie** [comment]
I was already thinking about the hex. I'm perhaps assuming that people won't find that clear enough, but that should be left up to the tests to find out. If you'd like, let's put the author's name(s) there, without a link to the profile.

**Comment by jameslibscie** [comment]
- [ ] Replace "not yet published..." text with author name(s). Text may be white or grey, whichever you (and @psobrakseaton) prefer
- [ ] If I open a published module from the workspace, clicking on the author name now takes me to the workspace. It should take me to the profile page.

Sorry about the back and forth on the author names thing. I think you make really valid points and I'd like to also get more of this out of the way first before work starts next time. Already have some ideas for that, which we can discuss during the `v0.1` retrospective :)

**Comment by juliangruber** [comment]
> I was already thinking about the hex. I'm perhaps assuming that people won't find that clear enough, but that should be left up to the tests to find out.

👍 😁  aye aye!

**Comment by juliangruber** [comment]
implemented :)

**Comment by jameslibscie** [comment]
Perfect! :)
