### ISSUE TITLE
Loading indicators

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/desktop#172]
Figma: [Loading indicators - #172](https://www.figma.com/file/jmlVL9WSgJZK8jqpGo4tL9/Loading-indicators?node-id=0%3A1)

Scope:
What animation do we want to show when something is loading. We want this to be consistent across elements. From button loading to full page profile loading.

Design Specs:

- [ ] Briefly explore loading indicators/animations.
- [ ] Explore how the current loading animation can be used in further contexts.

Questions:
- Are there any particular applications for the loading indicator that are currently missing?

**Comment by chartgerink** [comment]
AFAIK this is missing right now (will update if I find more):

* Loading profile's content

As I mentioned in our chats, I would suggest to use the same one as when the button "Add to profile" is clicked. That way when we update this proto we update the loading state everywhere later, plus we can close this rather quickly. I don't think we should spend too much time right now on designing a custom loading animation, given that we parked the animations aspect in general so it would require quite some learning.

**Comment by jameslibscie** [comment]
Does this issue also encompass creating a loading state for a content module that isn't fully downloaded?

**Comment by chartgerink** [comment]
![](https://media.giphy.com/media/6cFcUiCG5eONW/giphy.gif)

**Comment by psobrakseaton** [comment]
Link from @juliangruber: [https://loading.io](https://loading.io)

**Comment by chartgerink** [comment]
These are the places @juliangruber and I documented a loading state is needed:

* Feed screen
* Profile screen
* Discover screen (#274)
* Content screen (if not completely downloaded)

**Comment by psobrakseaton** [comment]
For the macro loading indicators (where we are loading entire sections, we should use the following format:

- [ ] The background color (black in this case)
- [ ] Centered loading indicator
- [ ] 32x32 dots for the animation (green and blue like the other implementations)

![Screen Shot 2020-09-21 at 11 56 42](https://user-images.githubusercontent.com/28573875/93754817-95b4a700-fc02-11ea-8740-bbad18af233d.png)

This should work for all the instances that @chartgerink mentioned above. @juliangruber let me know if there is further information needed for this task in particular. I'm gonna try to be moving fast today 🐎
