### ISSUE TITLE
Display at various OS zoom levels

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/desktop#175]
Figma: [Display at various OS zoom levels - #175](https://www.figma.com/file/qoROaGhDMtNyDVFu6Zmy7C/Display-at-various-OS-zoom-levels-175?node-id=0%3A1)

Specs:
TBD

**Comment by psobrakseaton** [comment]
@jameslibscie Could you please elaborate on this issue and propose some specifications?

**Comment by jameslibscie** [comment]
On windows, you can set the zoom at OS level. It's quite common for Windows 10 machines to be set to 125% or 150% zoom. This basically enlarges most elements of the application, but means that for common resolutions, some parts of the screen like the welcome modals run off the top and bottom of the screen. This in itself isn't so bad, but is good to take into account with the accessibility audit - does anything run off-screen when using higher (or lower?) levels of OS zoom.

**Comment by psobrakseaton** [comment]
> On windows, you can set the zoom at OS level. It's quite common for Windows 10 machines to be set to 125% or 150% zoom. This basically enlarges most elements of the application, but means that for common resolutions, some parts of the screen like the welcome modals run off the top and bottom of the screen. This in itself isn't so bad, but is good to take into account with the accessibility audit - does anything run off-screen when using higher (or lower?) levels of OS zoom.

Thanks for this, James! While we have some minor issues (i.e. the static size of the welcome modals) the app performs quite well all the way to max zoom levels. We currently don't have plans to responsively change the welcome modals and the time for that isn't in this cycle. I will park the task for later review.
