### ISSUE TITLE
Hover state to indicate clickability for content in content list

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/desktop#179]
Figma: [Hover state to indicate clickability for content in content list - #179](https://www.figma.com/file/7YkZCwRtGRtGtz59cMwuiI/Hover-state-to-indicate-clickability-for-content-in-content-list?node-id=0%3A1)

Specs:
TBD

**Comment by psobrakseaton** [comment]
@jameslibscie @chartgerink @juliangruber Currently upon hover the "+" for adding follow-from content. Is this indications enough for hovering, or is there something I am missing?

**Comment by jameslibscie** [comment]
Everything else that is clickable has a hover state that suggests clickability. The content list displays a +, but this only suggests that the + is clickable, as that has its own hover state. Furthermore, the + won't be displayed for draft content any longer as per #162 . Something like a background, border or cursor indication seems good to me. Or an arrow icon that appears on the right of the module.

**Comment by psobrakseaton** [comment]
Is the need for more obvious clickability an item based upon feedback or are we presuming confusion?

**Comment by jameslibscie** [comment]
It's based on feedback from a couple of testers - but everyone gets the hang of it - hence why it's a stretch goal rather than important.

**Comment by psobrakseaton** [comment]
Perfect. I think I have a very simple solution that might make this a non-issue. Hopefully this stitch goal can be accomplished this cycle.
