### ISSUE TITLE
Data explainer for adding files to content module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#19]
**User story**
As a Hypergraph user
I want to see a brief explanation of what happens with my files when I add them to a module
so that I know which files I can / should update
and so that I feel safe and in control of my content

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- The explainer is displayed if the user doesn't have any content yet
- If the user already has content, there is the ability to view the explainer again
- The explainer should contain the following points *(see designs for text)*
    - Where the files are located
    - What happens to the original files
    - How the user should work from now on

**Comment by jameslibscie** [comment]
Here's my suggestion for this one. Opinions @chartgerink @psobrakseaton ?

##### What happens with these files?

The files you select are copied to the Hypergraph folder. You can easily find the folder your files are located in via Hypergraph, using the *open folder* :open_file_folder: button.

You can choose to delete the original files or keep them. Please note that updates you make to the original files will not affect your content in Hypergraph. You can import the updated files again using Hypergraph or copy them over to the Hypergraph folder manually.

You can also choose to work in the Hypergraph folder. Hypergraph will automatically scan these folders for changes.

**Comment by chartgerink** [comment]
> ##### What happens with ~these~ your files?
> 
> ~The files you select~ We copy selected files ~are copied~ to the Hypergraph folder. You can easily find the*se* folder*s* ~your files are located in via Hypergraph~, using the _open folder_ 📂 button.
> 
> You can *always* choose to delete the original files or keep them. Please note that updates you make to the original files will not be seen ~affect your content in~ by Hypergraph. You can re-import ~updated~ files ~again~ using Hypergraph or copy them over to the Hypergraph folder manually.
> 
> You can also choose to work in the Hypergraph folder. Hypergraph will automatically ~scan~ see ~these folders for~ those changes.

I am unsure of the context this will be placed in, so it might need some adjustments later.

Thanks @jameslibscie!

**Comment by jameslibscie** [comment]
There is very little space in the current design, so I've tried this:

> These files are copied to Hypergraph. If you want to work on them further, you can choose to work using Hypergraph’s copies or reimport the files into Hypergraph when you’re done.

**Comment by jameslibscie** [comment]
This one has basically been absorbed by #16

**Comment by jameslibscie** [comment]
@juliangruber I just realised that the code for this is not done yet. It's part of the add content page and is in the designs, but not part of the app yet. Will you still have time for this?

**Comment by juliangruber** [comment]
@jameslibscie are there designs for this?

**Comment by jameslibscie** [comment]
@juliangruber Yep, you can find it here: https://www.figma.com/file/mkv0adXAq2sWF1unAmFDgl/desktop-current?node-id=159%3A43

**Comment by jameslibscie** [comment]
@juliangruber Given the designs, I see this working like:
- First content module, the icon is shown with the explainer open (like in the designs)
- Clicking the icon opens and closes the explainer
- Later modules, the icon is shown but with the explainer closed by default

**Comment by juliangruber** [comment]
Patch said this will only be visible on hover, need clear instructions :P

**Comment by juliangruber** [comment]
I would propose to move this to its own issue as this isn't important for the demo

**Comment by jameslibscie** [comment]
Hover is also fine :) but I'd preferably have it show open without having to hover when adding your first content.

**Comment by juliangruber** [comment]
I will implement one of both once you two decide

**Comment by jameslibscie** [comment]
Then let's go for the click, as I think it's useful for the information to stay visible while users are doing other things. Feels more "solid" that way.

**Comment by juliangruber** [comment]
I won't decide this over Patch. Please you two discuss this.

**Comment by jameslibscie** [comment]
Decided with @psobrakseaton & @juliangruber:
For now we will leave out the tooltip and just show the information as text underneath the *Upload files* header. I will update specs in original comment.

**Comment by juliangruber** [comment]
This version has been implemented. What shall we do with the issue?

**Comment by jameslibscie** [comment]
Close it! :)
