### ISSUE TITLE
Main menu ordering

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#192]
**Is your feature request related to a problem? Please describe.**
The tab order is currently based on implementation order (legacy).

**Describe the solution you'd like**
A discussion surrounding ordering with an agreed upon implementation.

**Describe alternatives you've considered**

* Alphabetical ordering
* Frequency of access (estimated)

**Additional context**

This was first mentioned in #165. @psobrakseaton already proposed an order there

*    Feed
 *   Drafts
  *  Following
   * Profile

**Comment by jameslibscie** [comment]
I think it would be valuable to group based on "own content" vs "remote content", so something like:

- Drafts
- Profile
- Feed
- Following

It makes the most sense in a "social media" context to have Feed first, but it depends whether we want to have the emphasis on reading / discovery or writing / creation. I'd say - for now - on writing / creation.

**Comment by psobrakseaton** [comment]
> I think it would be valuable to group based on "own content" vs "remote content", so something like:
> 
> * Drafts
> * Profile
> * Feed
> * Following
> 
> It makes the most sense in a "social media" context to have Feed first, but it depends whether we want to have the emphasis on reading / discovery or writing / creation. I'd say - for now - on writing / creation.

After reading the rationale, I think this makes a lot of sense for now. I would +1 this idea, but my main concern is whether or not we should go with expectation based orientation (feed first, profile last) as it is more familiar, or if we should do the grouping like you suggest.

**Comment by juliangruber** [comment]
> I think it would be valuable to group based on "own content" vs "remote content", so something like:

The Feed will also show your own content, and is most usually the default view (eg Twitter). I prefer Feed, Drafts, Following, Profile, because it makes sense from a workflow perspective. First you go to the Feed, to check out what's new. Then you go to your Drafts, to work on your content, or check out what's there. Following and Profile are useful too, so come afterwards.

**Comment by jameslibscie** [comment]
I think it's a cool statement to go against the norm and *not* put endless scrolling and distraction centre stage, but rather have it there for when people actively want to find new stuff.

@juliangruber Let's use #165 for whether the feed should contain own content. I'm not sure it should, but I'm open to hearing reasons to include it :)

**Comment by jameslibscie** [comment]
Seeing as we're integrating own content into the Feed and want to stick to known patterns, I'd go for:

- Feed
- Drafts
- Profile
- Following

And we can later integrate "Following" into the profile itself, which would also enable you to see who other people are following.

**Comment by juliangruber** [comment]
I'm closing this now, as there's nothing to be done (current order is Drafts, Profile), this now serves as a reference for future work.
