### ISSUE TITLE
Footer doesn't stick to bottom

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#194]
![image](https://user-images.githubusercontent.com/10247/88772232-bf140200-d180-11ea-854c-6869c07e1bf2.png)

It should be below all content, but if there is more space, stick to the bottom of the window.

**Comment by juliangruber** [comment]
@psobrakseaton there are occasions where the footer seems to stick to bottom, and some where it doesn't. Eg:

![image](https://user-images.githubusercontent.com/10247/88772427-11552300-d181-11ea-820f-5b3cc5902cfd.png)

How is this defined?

**Comment by juliangruber** [comment]
Or is it not actually sticking to bottom in the first screen?

**Comment by psobrakseaton** [comment]
Yeah, this is something that has bothered me for a while...There are are places where it is up at the top (which doesn't make any sense for the footer) and places where it is at the bottom (like you've shown).

There was some point where the footer became the stand-in for the empty list and really that should be a separate item. I'll think about this alter today. I don't think it is emergency level, but it definitely should change soon before it becomes too pervasive.

**Comment by psobrakseaton** [comment]
> @psobrakseaton there are occasions where the footer seems to stick to bottom, and some where it doesn't. Eg:
> 
> ![image](https://user-images.githubusercontent.com/10247/88772427-11552300-d181-11ea-820f-5b3cc5902cfd.png)
> 
> How is this defined?

After thinking about this for a bit, I think one of the main problems is that we are using a singular element that should really be split up. In the examples you posted, the left example of the footer being on the bottom with a message is working as intended, but in the second example the footer is acting as the top message.

In these cases, how difficult would it be to split it so that the message stays up at the top, but the "made in Berlin" message is moved to the bottom?

**Comment by juliangruber** [comment]
> In these cases, how difficult would it be to split it so that the message stays up at the top, but the "made in Berlin" message is moved to the bottom?

This makes sense and is reasonable to implement :+1:

**Comment by psobrakseaton** [comment]
> > In these cases, how difficult would it be to split it so that the message stays up at the top, but the "made in Berlin" message is moved to the bottom?
> 
> This makes sense and is reasonable to implement 👍

Perfect! If that's the case we should definitely do that. I'll look through the app and try to find the places where this would need to be implemented in this way and report back.

**Comment by psobrakseaton** [comment]
Ok, the areas where this would be useful is pretty self-evident, each tab (feed, drafts, profile, following) has its own empty state and the footer should be split.

So for the sake of obviousness, here's the list:

- [ ] Feed (empty)
- [ ] Drafts (empty)
- [ ] Profile (empty)
- [ ] Following (empty)
