### ISSUE TITLE
Error when opening remote profile

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#196]
## Description

I'm trying to open a profile from another machine. Tried with my own profile and Chris's profile. It doesn't matter whether I have a local copy of the profile. When I enter the link under "Find" and press enter, I get the following error:

![image](https://user-images.githubusercontent.com/59870484/88780760-c260bb00-d18b-11ea-8639-701e9c7251ec.png)

And a blank page then displays (Drafts is highlighted).

One time, it updated the current content page with the metadata from the profile, but I can't reproduce this.

I have tried resetting my p2pcommons DB and it still occurs.

## To Reproduce

1. Click "Find"
2. Input link to remote profile
3. Open
4. Error displays

## Expected behavior

Profile opens

## Actual behavior

Error is displayed 

## System

- OS (incl. version): Windows 10
- Hypergraph Desktop version: 0.4.0 at [97107f14b434ea1c44dcd23c63f24654aa4098c6](https://github.com/hypergraph-xyz/desktop/commit/97107f14b434ea1c44dcd23c63f24654aa4098c6)

**Comment by juliangruber** [comment]
Sorry about that!
