### ISSUE TITLE
chatra hides up arrow

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#199]
![image](https://user-images.githubusercontent.com/10247/88821067-74b37500-d1c2-11ea-81e8-24c430ce1d74.png)

The up arrow in the footer is hidden behind chatra.

**Comment by psobrakseaton** [comment]
Is the up arrow just under the chatra icon? If so I say we just blast the arrow out the airlock. Thoughts?

**Comment by juliangruber** [comment]
Correct, it's under it. I haven't used it yet either, but maybe that would change when having more modules. I'm cool with removing it.

**Comment by psobrakseaton** [comment]
Perfect. I already thought it was removed. Let's get rid of it until we need it. I feel like this is a more of a web interaction anyways.
