### ISSUE TITLE
Add files to existing content module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#20]
**User story**
As a Hypergraph user
I want to add files to my existing content
so that I can manage my in-progress work in Hypergraph

**Acceptance criteria**
- [ ] The content view page contains a button for adding files (same functionality as #16)
- [ ] The data explainer (#19) is accessible from within this interface
- [ ] If a new file matches an existing file, the user is presented with a choice to overwrite, rename the new file, rename the old file or skip
- [ ] If there are no files, the text "No files" is displayed

**Comment by juliangruber** [comment]
Is this just for adding files, or managing files in general? Eg can you also remove and edit files through this?

**Comment by jameslibscie** [comment]
Just adding for now. Everything regarding deleting / removing / unpublishing etc. is in block 3. They can already remove by manipulating the files in the folder directly. Of course they can also add files that way as well, so I might prioritise this lower.

**Comment by jameslibscie** [comment]
Completed via #228
