### ISSUE TITLE
fix modal accessibility

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#200]
https://bitsofco.de/accessible-modal-dialog/

**Comment by chartgerink** [comment]
We're also running the accessibility audit this workcycle --- will refer to this issue there as well :) If you have more accessibility comments, feel free to send them to @psobrakseaton or me :)

**Comment by juliangruber** [comment]
I noticed this implementing keyboard navigation for the app. Just tabindex isn't enough, as eg they say you should focus the first interactable element of the modal when it's opened

**Comment by chartgerink** [comment]
Yea I've been noticing areas for improvement with respect to keyboard navigation as well across the board. Will ping for review once the audit is more advanced, but you can always check the state on [Notion](https://www.notion.so/libscie/Accessibility-audit-2bb1a5e4ce814074babfc5bb9f8b3e1f).

**Comment by jameslibscie** [comment]
Is this issue still relevant? @chartgerink @juliangruber

**Comment by juliangruber** [comment]
Yes! Try using modals with a keyboard
