### ISSUE TITLE
Certificates for Windows / Mac

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#21]
**User story**
As a Hypergraph user
I want to be able to run Hypergraph without security warnings or altered security settings
so that I feel comfortable using the application

**Acceptance criteria**
- [x] An Apple Developer account is created for Liberate Science or Hypergraph
- [x] A certificate is obtained for the Hypergraph Mac app
- [x] This certificate is implemented into the Hypergraph Mac app
- [x] A certificate is obtained for the Hypergraph Windows app
- [x] This certificate is implemented into the Hypergraph Windows app

**See also**
[Get a code signing certificate for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate)
[Code signing for Electron apps on Windows](https://www.electron.build/code-signing#windows)
[Apple Developer](https://developer.apple.com/)

**Comment by juliangruber** [comment]
Sure!

> 1. Why this is necessary? I.e., what the consequences are of _not_ having this

Certificates are required for code signing, which is a mechanism provided and checked by the operating system to verify the author of a software is who they claim to be. This thus serves the user's need for security. macOS for example doesn't let you open unsigned apps unless you press a certain button the System Preferences and try again.

> 2\. What needs to be done to arrange this?

We need a ADC account for macOS, from which we can export the certificate, and here's docs for Windows: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate?redirectedfrom=MSDN.

**Comment by jameslibscie** [comment]
I've updated the main issue. I think it makes sense to get started on this quickly, so we can provide people with a secure, working product when the time comes. I imagine there might be some waiting time involved with Apple?

Does it make sense for @chartgerink to sort this out?

**Comment by juliangruber** [comment]
There's no waiting time, so I'll leave the timing to you :)

**Comment by chartgerink** [comment]
@jameslibscie if you want to coordinate on this let me know. I am happy to foot the bills; maybe having @juliangruber as lead engineer own the credentials makes sense?

**Comment by juliangruber** [comment]
I'm happy to set this up by signing up for both services and then exporting the certificates, or @chartgerink you could sign up with the CC details and then let me use the accounts?

**Comment by juliangruber** [comment]
The cheapest offer I found is 349$/year if we pay yearly, or 249$/year for 3 years:

![Screenshot 2020-02-10 at 15 24 39](https://user-images.githubusercontent.com/10247/74157979-8ce60680-4c19-11ea-8ea5-ef3037009ac2.png)
https://www.ssl.com/certificates/ev-code-signing/buy

**Comment by juliangruber** [comment]
Shall we wait with this until we say Hypergraph Desktop isn't just for developers any more? I don't see a reason to buy a certificate before that, especially with yearly payments.

**Comment by chartgerink** [comment]
I'll put it on my tasklist as not high priority but if I get around to it I can just start setting things up. If we pay 3 months more that doesn't matter that much. We might bump it if we start noticing it becoming a nuisance with our user community.

**Comment by jameslibscie** [comment]
Does it make sense to perhaps sort the Mac certificate out soon and do the Windows one later? 
Given:
> macOS for example doesn't let you open unsigned apps unless you press a certain button the System Preferences and try again.

**Comment by juliangruber** [comment]
I think we can just be lazy about it, let's get a certificate once it becomes a problem to not have one. Real priorities are observed, not defined 🤷‍♀

**Comment by chartgerink** [comment]
Related issue https://github.com/hypergraph-xyz/hyperdrive-daemon-app/issues/21

**Comment by chartgerink** [comment]
Liberate Science GmbH now has an Apple Developer account and @juliangruber has been invited to create a developer account.

After looking around a tiny bit I think the certificates can be created on [this page](https://developer.apple.com/account/resources/certificates/list) (after login).

**Comment by juliangruber** [comment]
Certs created! 🥳

**Comment by chartgerink** [comment]
Status update: SSL.com complained that they didn't have a phone number on file. I needed to change it with the DUNS organisation, which is taking a while to propagate (like  DNS). Hopefully we'll have the certs end of next week...

**Comment by chartgerink** [comment]
Status update: Phone number verified on 20-07-2020, pinged just now to escalate because #158 is also blocked by this.

More to follow...

![](https://media.giphy.com/media/ERMGXqtKTDKHC/giphy.gif)

**Comment by juliangruber** [comment]
@chartgerink we messed this one up. We could have gotten either an `EV Code Signing Certificate`, or a regular `Code Signing Certificate`. The EV is the one with the dongle that can't be exported, hence it can't be made to work in CI environments. SSL.com also offers these https://www.ssl.com/certificates/code-signing/, however this webpage currently seems to be broken.

Can we talk to them about getting a different certificate, and hopefully a refund on the old one?

**Comment by juliangruber** [comment]
Tutorial for code signing using an EV certificate: https://interactiveknowledge.com/insights/how-code-sign-electron-app-windows
