### ISSUE TITLE
Unknown (new) error upon Find profile

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#210]
## Description

Unknown error upon fetching profile.

## To Reproduce

1. Setup Hypergraph
2. Share profile
3. Paste link in "Find"

## Expected behavior

Retrieve profile.

## Actual behavior

Error.

## Screenshots

<img width="1552" alt="Screenshot 2020-08-05 at 15 12 30" src="https://user-images.githubusercontent.com/2946344/89416797-16d8dd00-d72e-11ea-8003-05f511f8a5dd.png">

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: [0.5.4 release 209](https://github.com/hypergraph-xyz/desktop/actions/runs/196233388) 

## Additional context

Works normally in official 0.5.4 release.

**Comment by juliangruber** [comment]
Fixed in https://github.com/hypergraph-xyz/desktop/pull/209/commits/e9568233fbb9548008f53517e74c6a9c6bc74cd9
