### ISSUE TITLE
Cancel button on Add Content screen incorrectly aligned

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#212]
![image](https://user-images.githubusercontent.com/59870484/89425984-ee56e000-d739-11ea-8be3-68aeec92b9fe.png)

I broke this with my changes to `Anchor`. Want me to fix it @juliangruber?

**Comment by juliangruber** [comment]
> I broke this with my changes to `Anchor`. Want me to fix it @juliangruber?

Sure go for it!

**Comment by chartgerink** [comment]
@jameslibscie is this also causing the weird alignment for the content cards? Seems like there is too little spacing there.

![Screenshot 2020-08-05 at 18 15 40](https://user-images.githubusercontent.com/2946344/89437386-c9696980-d747-11ea-9dd6-3567a3df944e.png)

**Comment by jameslibscie** [comment]
Yes, that's caused by the same bug.

**Comment by jameslibscie** [comment]
This issue can also be closed as #208 was reverted
