### ISSUE TITLE
Content title too large on content page

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#213]
![image](https://user-images.githubusercontent.com/59870484/89428707-fcf2c680-d73c-11ea-8c0d-939187da87e2.png)

See figma on left, app on right

**Comment by juliangruber** [comment]
This was done in https://github.com/hypergraph-xyz/desktop/commit/c6d61d6dfaa53fc4a538df527711d509a0c74323, and you're right that it overshot the target.

@psobrakseaton the Heading 2 style in figma has a line height of 30px (1.25rem) and a margin bottom of 16px (1rem), making it 36px high. The heading in this design has a line height of 42px (3rem) and no margin-bottom, making it 42px high. Could you please consolidate this?

**Comment by psobrakseaton** [comment]
> This was done in [c6d61d6](https://github.com/hypergraph-xyz/desktop/commit/c6d61d6dfaa53fc4a538df527711d509a0c74323), and you're right that it overshot the target.
> 
> @psobrakseaton the Heading 2 style in figma has a line height of 30px (1.25rem) and a margin bottom of 16px (1rem), making it 36px high. The heading in this design has a line height of 42px (3rem) and no margin-bottom, making it 42px high. Could you please consolidate this?

Thanks for pointing this out. I will remedy it ASAP.

**Comment by jameslibscie** [comment]
@psobrakseaton @juliangruber Little reminder that this is still open and probably a very quick fix
