### ISSUE TITLE
Error: Something went wrong with delete

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#217]
## Description

During user testing, @juliangruber tried to delete modules that were on his profile. This action only removed the modules from his profile. The error `Something went wrong with delete` showed in the console.

## System

- OS (incl. version): Windows 10
- Hypergraph Desktop version: 0.5.4 #215, also occurs with 0.6.0

**Comment by jameslibscie** [comment]
Can't retest this due to https://github.com/hypergraph-xyz/desktop/issues/227

**Comment by juliangruber** [comment]
Using the latest sdk version, even if I deregister first the error still appears. It would be great if the actual error message showed.

**Comment by juliangruber** [comment]
This is still blocked, as the error seems to be with the sdk

**Comment by juliangruber** [comment]
https://github.com/p2pcommons/sdk-js/issues/234

**Comment by juliangruber** [comment]
I can't reproduce this any more
