### ISSUE TITLE
Delete removes unversioned folder only 

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#219]
## Description

When I delete content, it removes the unversioned folder only.

## To Reproduce

1. Create content module with main
2. Add to profile
3. Note the hyperdrive key
4. Go to ~/.p2pcommons
5. Delete registered content
6. Check ~/.p2pcommons

## Expected behavior

I expect the application to delete the relevant folders on my computer.

## Actual behavior

It only deletes unversioned folders and ignores versioned folders.

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: 0.5.4

## Additional context

I think this is legacy of the delete content button for the drafts, where it is always unversioned. When it's registered and entered through either the feed or the profile, it is a versioned folder. I think the issue is in [this line of code](https://github.com/hypergraph-xyz/desktop/blob/c56071841a52ade0ef5f424bf7522783c8b584ba/app/components/content/content.js#L335) and that it does not differentiate for registered and unregistered content.

**Comment by juliangruber** [comment]
This is an SDK issue as Desktop just calls `p2p.delete` and doesn't manually delete files.

**Comment by chartgerink** [comment]
Yea --- is a `p2p.delete` with a versioned URL where relevant not sufficient to implement this in desktop? Or would `p2p.delete` require an adjustment first?

**Comment by juliangruber** [comment]
`p2p.delete` accepts a `key` only, and then deletes the unversioned folder:

https://github.com/p2pcommons/sdk-js/blob/1d8db8c071398d7f30600d42ba8c853f2ae6d328/index.js#L1687-L1692

**Comment by juliangruber** [comment]
```js
      const drivePath = join(this.baseDir, keyString)

      if (deleteFiles) {
        debug(`Moving drive folde ${drivePath} to trash bin`)
        await trash(drivePath)
      }
```
