### ISSUE TITLE
"electron-devtools-installer" error when installing and opening Hypergraph on Windows

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#22]
**Describe the bug**
When opening Hypergraph (this occurs directly after installation as well), an error window pops up
![Hypergraph installer error](https://user-images.githubusercontent.com/59870484/73848523-8d049180-4828-11ea-8cb7-2248f40fd2de.jpg)

The installation itself appears to complete correctly. I.e., a desktop shortcut is placed and the application can be uninstalled from within Windows *Apps & features*

**To Reproduce**
1. Install Hypergraph on Windows (10?) -> error message pops up
2. Open Hypergraph -> error message pops up

**Expected behavior**
There should be no error

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
We have already checked whether it has to do with the `NODE_ENV` environment variable and it does not seem to be related. My PC does not have `NODE_ENV` set and node also returns `process.env.NODE_ENV=undefined`. [See here for a situation in which the same error occurs due to `NODE_ENV='development'`](https://community.atlassian.com/t5/Stride-questions/Stride-desktop-for-Windows-10-quot-Cannot-find-module-electron/qaq-p/801064#M2188)

**Comment by juliangruber** [comment]
I can reproduce 🎆 

![Screenshot 2020-02-07 at 14 03 15](https://user-images.githubusercontent.com/10247/74031753-9c174b00-49b2-11ea-935b-5b28d2efe0b9.png)
