### ISSUE TITLE
Write profile to settings.json

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#221]
**Is your feature request related to a problem? Please describe.**
The p2pcommons interoperability spec includes the `defaultProfile` key/value pair. It remains empty at the moment.

**Describe the solution you'd like**
Write out the profile Hyperdrive key (created during the welcome modals) to the `defaultProfile` key/value pair.

**Describe alternatives you've considered**
-

**Additional context**
This came up up during the discussions with @dpaez surrounding #220

**Comment by juliangruber** [comment]
@chartgerink thanks for reporting this! would you consider this a release requirement?

**Comment by chartgerink** [comment]
No, not if it's unnecessary to resolve #220 --- we'll chat about this tomorrow more :)
