### ISSUE TITLE
logo not clickable

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#222]
![image](https://user-images.githubusercontent.com/10247/90391915-3527cc80-e08e-11ea-8da0-33a44cb5eb55.png)

The network status container overlays the logo

**Comment by psobrakseaton** [comment]
Yeah, this needs to be fixed asap. I will define a new clickable area for the logo.

**Comment by juliangruber** [comment]
This is an implementation bug really, i just need to shuffle some layers around. No design changes are necessary, but if you want to define a clickable area that's nice UX

**Comment by psobrakseaton** [comment]
> This is an implementation bug really, i just need to shuffle some layers around. No design changes are necessary, but if you want to define a clickable area that's nice UX

Cool cool. If that's the case I will define the area later. This is gonna be even more relevant when I work on the hover states for icons. They are gonna need areas as well.
