### ISSUE TITLE
Author missing from "Follows from" list

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#223]
![image](https://user-images.githubusercontent.com/10247/90485868-6a88f480-e138-11ea-9c8f-f8f39f5a0bed.png)

The module "test" is from Chris, the others I have locally. It would be great to be able to differentiate between the different authors. Maybe a format like "Name (Author)" or "Author: Name" could work.

**Comment by chartgerink** [comment]
For multi-author we could do `et. al` for now? :)

**Comment by jameslibscie** [comment]
I noticed from yesterday's test that people might also use duplicate titles across modules, using only the content type to differentiate. Maybe it's worthwhile to list the content type as well.

I would also suggest having the follows from format the same everywhere, so in this dropdown, on the mini-map tooltip and in the parent link on the content page.

**Comment by psobrakseaton** [comment]
Here's my proposal for how to format the text:

"Title - First Author et. al"

@chartgerink what do you think?

**Comment by chartgerink** [comment]
@psobrakseaton I would personally switch author and title, because reference lists are sorted on author as well. They follow:

`<AUTHOR> (<YEAR>). <TITLE>`

If we use that pattern (w/o year for now) we can leverage the recognition. Beyond that, I think the format works :)

**Comment by juliangruber** [comment]
Good thinking to follow existing patterns. That would then be like this, right?

```
<AUTHOR>. <TITLE>
```

or

```
<AUTHOR> et. al. <TITLE>
```

**Comment by chartgerink** [comment]
Exactly :)

**Comment by psobrakseaton** [comment]
> Good thinking to follow existing patterns. That would then be like this, right?
> 
> ```
> <AUTHOR>. <TITLE>
> ```
> 
> or
> 
> ```
> <AUTHOR> et. al. <TITLE>
> ```

Looks great to me! Lets roll with this!
