### ISSUE TITLE
Terms of use modal

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#225]
Hypergraph terms of use (see https://www.notion.so/Terms-2794527482b54eddb5b7c991e8152999) still need to be implemented in the app. The chosen implementation is to have them as the first page of the welcome modals with a button to accept.

I can do the implementation, but there is a design necessary for this screen. @chartgerink has made a proposal here: https://www.figma.com/file/kf9PzbeOIIsmCJfjtjUr8P/welcome-modals?node-id=121%3A285. @psobrakseaton could you check this and make changes if necessary?

**Comment by psobrakseaton** [comment]
[Here is the Figma for this task.](https://www.figma.com/file/9FxkbQ1YA0og2XjIqgEBie/220-Terms-of-use-modal?node-id=0%3A1)

The design will be updated shortly.

**Comment by psobrakseaton** [comment]
@chartgerink do we want the agreement button to be disabled until the whole terms of use section has been "read"?

**Comment by chartgerink** [comment]
Sounds like a considerate point for the design, so my first thought would be yes. What do you think?

**Comment by psobrakseaton** [comment]
I'm gonna go for yes. I think it is a pretty standard pattern, and worthwhile.

**Comment by psobrakseaton** [comment]
Ok, the design is pretty much ready to go. Tomorrow in W.O. it would be nice to give a 1 minute walkthrough to see if @juliangruber has all the info he needs. After that I'll write a comment with the parameters for success and we can implement it.

**Comment by juliangruber** [comment]
![image](https://user-images.githubusercontent.com/10247/91979601-4c211c80-ed26-11ea-8600-6a16dbf0b2b2.png)

@psobrakseaton looking at this, I wouldn't immediately know what I'd need to do. What about adding a text like "Please read the terms of use first"?

**Comment by juliangruber** [comment]
Also "any additional terms will be provided when relevant", when and where would this happen?

**Comment by chartgerink** [comment]
> Also "any additional terms will be provided when relevant", when and where would this happen?

If the terms change (eg. upon update) the modal would reappear and ask for permission again. 

Another scenario could be when we introduce payments in the app, that there are more conditions that would have to be accepted before being able to make a payment.

Do you think that's too much of a hassle? (either scenario)

## Other important info:

@psobrakseaton we would need a checkbox for the analytics, so that people can opt-out. We now state in the terms

> We collect analytics regarding how you use Hypergraph, except when you opt out during setup

If people hit agree and the checkbox is active (e.g., "Allow analytics to be sent to Liberate Science GmbH") we should inject the tracking code into the `<head>`. The exact code is [available in Notion](https://www.notion.so/libscie/Implement-website-desktop-analytics-a1736fde6d174ddb93068c8a54d80951#a2a1b1ce9a1d4ade82e30cbe35b68d0f).

Sorry about the lack of specs on this before.

**Comment by chartgerink** [comment]
PS: @juliangruber let me know when you need me to supply the terms in HTML and I will provide, doing some final revisions on those.

**Comment by psobrakseaton** [comment]
Ok, so in light of the new information, this is what I see as the specs:

- [ ] System checkbox pre-checked for analytics
- [ ] Distance between checkbox and button the same as the "Skip for now..." on the vault modal
- [ ] Agree button that can be clicked without scrolling
- [ ] No back button as this first modal

Anything missing?
<img width="724" alt="Screen Shot 2020-09-02 at 14 23 12" src="https://user-images.githubusercontent.com/28573875/91981153-b0dd7680-ed28-11ea-9c1f-66e5d25f17a8.png">

**Comment by juliangruber** [comment]
> If the terms change (eg. upon update) the modal would reappear and ask for permission again.

I thought it couldn't be that because it already says in the next sentence that wehn the terms change we will request your permission. Could either be removed?

> System checkbox pre-checked for analytics

Is pre-checked allowed for that kind of choice?

> Anything missing?

I think that should be all :+1:

**Comment by chartgerink** [comment]
You're right. Noted for the revisions of the Terms I'm doing tomorrow 👍 

AFAIK pre-checked is allowed as long as an option is given to uncheck without any additional hurdles. In firefox, the same happens with studies they run for example.

**Comment by psobrakseaton** [comment]
Done! Same as above. What's left is the properly formatted copy from @chartgerink

**Comment by juliangruber** [comment]
> Done! Same as above. What's left is the properly formatted copy from @chartgerink

Thanks, I updated the labels and assignee

**Comment by psobrakseaton** [comment]
> Thanks, I updated the labels and assignee

Perfect. I was answering from the app and couldnt find a way to edit that.

**Comment by jameslibscie** [comment]
Would it perhaps be valuable to emphasise that the analytics are anonymous? Or perhaps use a more neutral term like "statistics"?

**Comment by chartgerink** [comment]
Thanks for the tip @jameslibscie! Included it in the revision. 

The Terms are available as HTML file [here](https://drive.google.com/file/d/1_bGnh6cCSreifzOBsM_sHf6mu8_erlcg/view?usp=sharing). Styling from this HTML file can be dropped. In case of doubt, please refer to [the Notion page](https://www.notion.so/libscie/Terms-2794527482b54eddb5b7c991e8152999) or ping me :)

An additional pass will be needed when we add any payment integrations
