### ISSUE TITLE
Could not find index.json after deleting registered module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#227]
## Description

After deleting a registered module, the Feed and Profile both display this error:
![image](https://user-images.githubusercontent.com/59870484/90614132-8d83d900-e20a-11ea-81d9-375a99433e90.png)

This error also occurs after restarting Hypergraph.
## To Reproduce

1. Create content
2. Add to profile
3. Delete content
4. Error displays

## System

- OS (incl. version): Windows 10
- Hypergraph Desktop version: [0.5.4@fea957e](https://github.com/hypergraph-xyz/desktop/commit/fea957e417740dbba767cce1140a29df9c180af2)

**Comment by juliangruber** [comment]
I can't reproduce this because I only get the "Something went wrong with delete" error :/
