### ISSUE TITLE
No spaces between multiple authors

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#229]
## Description

Upon manually adding multiple authors to a content module, I noticed the content card and content window displays the authors without a space. 

## Expected behavior

Authors separated by spaces

## Screenshots

<img width="1552" alt="Screenshot 2020-08-19 at 15 10 32" src="https://user-images.githubusercontent.com/2946344/90638966-4dcee880-e22e-11ea-87df-b67db1944a3f.png">
<img width="1552" alt="Screenshot 2020-08-19 at 15 10 34" src="https://user-images.githubusercontent.com/2946344/90638983-53c4c980-e22e-11ea-9219-cbc1443c439f.png">

## Additional context

Manually added the authors :) Tried to use `.join(' ')` to introduce the space myself but didn't get there. Learned about ternary operators in the meantime!

![](https://media.giphy.com/media/xT5LMtNAWcVh4zCdaw/giphy.gif)

**Comment by juliangruber** [comment]
If you're curious, the implementation could be something like this:

```jsx
{authors.map(name => (
  <Author>{name}</Author>
  {' '}
))}
```

or cleaner could be to use CSS, like

```js
const Author = styled.a`
  /* ... */
  margin-right: 2px;
`
```
