### ISSUE TITLE
Open content folder

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#23]
**User story**
As a Hypergraph user
I want to open the folder that contains my content
so that I can see where my files are located and manipulate them as I would normally

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- The button to open the Dat archive folder should be located on the content view page
- The folder should open in the default way for the operating system
- The button should show even if the user has not added any files

**Comment by jameslibscie** [comment]
This seems to work already! Right now it opens in the background on Windows. Is there a way to open it in front?

**Comment by juliangruber** [comment]
Can you try ☝️ build?

**Comment by jameslibscie** [comment]
Ah, super nice! :D
