### ISSUE TITLE
Publish to profile

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#24]
**User story**
As a Hypergraph user
I want to publish content to my profile
so that work that I consider ready can be gathered in once place
and (later) be made visible and findable to others that are interested in my work

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- Only content modules that are writable by the user can be published to their profile
- After publishing, the profile module contains a `p2pcommons.contents` reference to the content module and vice versa in `p2pcommons.authors`
- After publishing, a list of all content in the profile's `p2pcommons.contents` shows on the profile page. This list can be used to navigate to a content page
- After publishing, a list of all authors in the content's `p2pcommons.authors` shows on the content page. This list can be used to navigate to an author's profile page
- After publishing, the author(s) for a content module show in the content list on the home page
- Published and unpublished modules should be visually distinguishable from one another on the Workspace page
- Before publishing, the content module is validated (according to [@p2pcommons/specs](https://github.com/p2pcommons/specs)) before publishing. If a module is invalid, this indicates that the user has made manual changes to the module OR that there is a bug in Hypergraph. The user should be shown a descriptive error and prompted to submit a bug report.
- Before publishing, it is checked whether the `main` file exists. If not, the user is instructed to make sure this file exists before retrying.
- After publishing, the content module is verified to check whether publishing has succeeded. If not, the user should be shown a descriptive error and prompted to submit a bug report via e-mail.
- Only published (versions of) content modules are displayed on the Profile page
- [DESIGN ONLY] Published modules show an "Unpublish" button instead of a "Publish" button

**Comment by juliangruber** [comment]
> * Before publishing, it is checked whether the `main` file exists. If not, the user is instructed to make sure this file exists before retrying.

I opened an SDK issue for this https://github.com/p2pcommons/sdk-js/issues/141

**Comment by juliangruber** [comment]
> * [DESIGN ONLY] Published modules show an "Unpublish" button instead of a "Publish" button

This has been implemented as well 🎆

**Comment by juliangruber** [comment]
Except for the first mentioned issue, all of this is done :)

**Comment by jameslibscie** [comment]
This works great! Thanks for opening the SDK issue :)
