### ISSUE TITLE
Files don't all show immediately after adding content

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#240]
## Description

When adding content with many files, sometimes the file list on the content page only shows the first few files. After refresh, all files show.

## To Reproduce

1. Add content with many files -> see that only a few files show on the content page

## Expected behavior

All files show up

## Actual behavior

Only some files show up

## System

- OS (incl. version): macOS 10.x
- Hypergraph Desktop version: 0.6.0

**Comment by chartgerink** [comment]
Can no longer reproduce.
