### ISSUE TITLE
Error when opening hypergraph:// url

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#245]
## Description

I've not seen this happen before, but it occurred once during a test. The user opened a `hypergraph://` url in Chrome and allowed the url to open in Hypergraph, then received this error:

![image](https://user-images.githubusercontent.com/59870484/91459570-0fb57280-e887-11ea-8d19-35f54d637190.png)

## To Reproduce

Might not be possible to reproduce
1. Open hypergraph:// url in Google Chrome
2. Let it open Hypergraph -> error may be displayed

## System

- OS (incl. version): macOS 10.x
- Hypergraph Desktop version: 0.6.0

**Comment by juliangruber** [comment]
This can only happen on mac and not Windows, because on mac you can have the app running but no window open. During the test the user must not have had the Hypergraph window open, but the app still running, when they clicked on the link.
