### ISSUE TITLE
Beta status indicator

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#259]
It would be great to mention in the welcome screens, and potentially in other places, that Hypergraph is beta software.

**Comment by psobrakseaton** [comment]
I think for the status indicator it would be best for it to state something like "Hypergraph (Beta)" in the application name.

It would be great if on the "Welcome to Hypergraph" modal we have that reflect the current application name. There may be other areas where we will want the application name to appear (aren't immediately clear now), but those can be added as we come across them. 

@chartgerink Do you think there are any other specific places in the app where we should have "Hypergraph (Beta)" displayed?

**Comment by chartgerink** [comment]
We could edit the text and title yea :) 

An idea might be to add an indicator on the logo top left? It could reflect the avatars for example.

**Comment by psobrakseaton** [comment]
Ok, I discussed it briefly with @chartgerink.

Here's the new parameters:

- [ ] Add "(Beta)" to the application name
- [ ] Have the application name reflected in the "Welcome to Hypergraph" modal

I'll have a look a the app today and see if there are other places for the app name.

**Comment by juliangruber** [comment]
> I'll have a look a the app today and see if there are other places for the app name.

@psobrakseaton did you finish this?

**Comment by psobrakseaton** [comment]
> > I'll have a look a the app today and see if there are other places for the app name.
> 
> @psobrakseaton did you finish this?

I was wondering, if the rules are set up to have the app name displayed (like `${appName}` sorta deal) would the technical barrier for adding it in different parts of the app be high?

In explanation, for now if we have the app only on the welcome modal we can make the decisions right now and change it for other places as we come across them in the future.

**Comment by psobrakseaton** [comment]
Ok! After a quick comb through, here are the two places for it:

- [ ] Add "(Beta)" to the application name
- [ ] Have the application name reflected in the "Welcome to Hypergraph" modal (modal after terms)

Thanks, Juli!
