### ISSUE TITLE
Handle case where author isn't available on the network

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#266]
Eg you look at a module with multiple parents and one of the parents isn't available (locally or over the network).

**Comment by juliangruber** [comment]
@psobrakseaton we'll need design for this case. If an author isn't available on the network, all we know is their "ugly" key, nothing else. How to display this author in the module screens?

**Comment by juliangruber** [comment]
When an author isn't available on the network, we need to define a timeout for that. It's impossible to know right away whether it will be available, just like with the Find modal. So we also need a loading state for the individual author name.

**Comment by psobrakseaton** [comment]
From our meeting:

States needed:
- [ ] Author Name (Everything OK)
- [ ] "Author Unknown"
- [ ] Loading state (unsure)

**Comment by psobrakseaton** [comment]
Alright, here's the async walkthrough of this task so far...

The everything OK/author-known state is self explanatory:
![author-known](https://user-images.githubusercontent.com/28573875/93896759-9b3cea80-fcf1-11ea-97c1-7305ab7f0290.png)

The author-unsure/loading state would have the a small spinner (roughly 16px) wherever the unknown author is. Should this not be possible, the loading spinner should just be on the author area in general:
![author-loading](https://user-images.githubusercontent.com/28573875/93897097-f838a080-fcf1-11ea-9c9d-0fd610bcf1fd.png)

The last state is if the author is looked for and can't be found in which case we state "Author Unavailable" in libscie-gray: 
![author-unavailable](https://user-images.githubusercontent.com/28573875/93897178-0f778e00-fcf2-11ea-9d49-c1831ed36a1f.png)

The loading indicator SVG area is 32px across (8px padding + 16px spinner + 16px padding) and should have a comma between the spinners as the authors will replace them. 

We should touch base before we reassign this project in case there are states or technicalities that I haven't accounted for yet.

**Comment by juliangruber** [comment]
I think this should work! 😍
