### ISSUE TITLE
Discover screen

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#274]
**Is your feature request related to a problem? Please describe.**
At the moment, users cannot see any example content and learn from other users on what Hypergraph is capable of, when they start out and have nobody to follow (presumably).

In SSB and Rotonde, it wasn't uncommon to lose people's interest because there was no example content. The cold-start issue might be one we also face with Hypergraph.

**Describe the solution you'd like**
The Vault has a feed of new content, that could be the basis of seeing content and find people to follow. If we'd have X most recent additions in a separate screen (e.g., "Discover") on its own, people could find content and people without clogging their feed directly. 

We could for example only take the ten most recent, and download the next ten if people hit the bottom of the screen to create an infinite scroll (if we want to).

We could limit it to content only so no design for profile cards would be needed in the feed (or we could use the one from "Following", maybe?).

**Describe alternatives you've considered**
Adding some random profiles to the "Find" modal to click on. Might require more design work.

**Additional context**
This is a stretch goal for cycle ~6~ 5. During the walkthroughs, it appeared that people would like this.

**Comment by juliangruber** [comment]
If we don't do infinite scrolling and just render latest X content modules that could work well during this cycle 👍

**Comment by psobrakseaton** [comment]
[Here is the Figma for this issue.](https://www.figma.com/file/P0QZTesp3c56QHXjvFEy9V/274-Discover-screen-missing-content?node-id=0%3A1)

The copy is as follows:

Type ---> "Unknown"
Title ---> "Content (temporarily) unavailable"
Description ---> "There is nobody to download this content from at the moment. Please try again later."

**Comment by psobrakseaton** [comment]
Just saw there is more to be done. I'll update when the task is complete.
