### ISSUE TITLE
Reset database fails

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#279]
## Description

When resetting the database in Hypergraph, it crashes the application (window closes) but doesn't throw an error outside of the terminal.

## To Reproduce

1. Open Hypergraph
2. Create profile
3. Register some content to profile
4. Reset database

## Expected behavior

Reset database and open up Hypergraph as if it's a clean install.

## Actual behavior

Window crashes upon "Reset database". Upon reboot, database is not reset either.

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: https://github.com/hypergraph-xyz/desktop/commit/5490c75d344fed186cc836f8f38e01f87861c678

## Additional context

Error code:

```
(node:15888) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Users/chjh/.p2pcommons/<hash>+<version>/index.json'
```

**Comment by juliangruber** [comment]
This fails due to a node core bug: https://github.com/nodejs/node/issues/23736

If I find time for it post release I'll try to fix it there, but for now I'll have to find another way around it
