### ISSUE TITLE
Co-authored content doesn't show up in drafts

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#280]
## Description

When somebody I follow assigns me as a co-author on content, it does not show up in my Drafts. This would still require an action on my end, because I remain an unverified author until I also add it to my profile.

## To Reproduce

1. Find a friend
2. Exchange Hypergraph links
3. Let them follow you (and you follow them)
4. Let them add a piece of content to their profile with you as co-author
5. Wait for the information to pop up in your Hypergraph

## Expected behavior

Co-authored content shows up in Feed AND Drafts.

## Actual behavior

Co-authored content shows up in Feed but not Drafts.

## Screenshots

![Screenshot 2020-09-17 at 10 52 22](https://user-images.githubusercontent.com/2946344/93761426-0f05c700-fc0e-11ea-8660-ceba744a3d13.png)
![Screenshot 2020-09-17 at 10 52 24](https://user-images.githubusercontent.com/2946344/93761428-1036f400-fc0e-11ea-8a28-92ab1dab5ecb.png)

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: 94f00c3fc586d327bdb3dff434fd65a1cd29e510

## Additional context

May run in to the synchronisation issue while reproducing this https://github.com/p2pcommons/sdk-js/issues/244

**Comment by juliangruber** [comment]
Blocked by https://github.com/p2pcommons/sdk-js/issues/246

**Comment by juliangruber** [comment]
Fix in https://github.com/p2pcommons/sdk-js/pull/247
