### ISSUE TITLE
Can't add co-authored content to profile

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#281]
## Description

When I co-author content, I would like to add it to my profile. I can't if the replication is incomplete, even if it already being registered by the other author(s).

## To Reproduce

1. Find a friend
2. Exchange Hypergraph links
3. Let them follow you (and you follow them)
4. Let them add a piece of content to their profile with you as co-author
5. Wait for the information to pop up in your Hypergraph
6. Open content
7. Click "Add to profile"

## Expected behavior

Adds the already registered content that I co-authored to my profile.

## Actual behavior

The content was not replicated completely, and fails to add to profile because the validations don't pass. 

## Screenshots

![Screenshot 2020-09-17 at 10 52 17](https://user-images.githubusercontent.com/2946344/93762038-242f2580-fc0f-11ea-8eac-40872a00d162.png)

## System

- OS (incl. version): macOS 10.15.6
- Hypergraph Desktop version: around 94f00c3fc586d327bdb3dff434fd65a1cd29e510

## Additional context

Related to https://github.com/p2pcommons/sdk-js/issues/244 for replication. Validation and adding to profile happens at `sdk` level so might not be a desktop issue?

**Comment by juliangruber** [comment]
The problem wasn't replication but rather that it tried to register an outdated version. This has been fixed in main 🥳
