### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by todrobbins** [hypergraph-xyz/desktop#308]
## Description
Launching version `0.8.0` of the app produces this error and then no content is viewable after clicking `OK`

## To Reproduce
1. Launch app
2. Click `OK` of error message

## Screenshots

![Screen Shot 2020-10-05 at 9 47 29 AM](https://user-images.githubusercontent.com/158590/95102015-163dd200-06f0-11eb-9f8f-051f50642818.png)

![Screen Shot 2020-10-05 at 9 49 45 AM](https://user-images.githubusercontent.com/158590/95102038-1e960d00-06f0-11eb-8bd6-832baf359aca.png)

## System

- OS (incl. version): macOS 10.15.7
- Hypergraph Desktop version: 0.8.0

**Comment by todrobbins** [comment]
I just checked and `0.7.0` loads/runs without any issues.

**Comment by juliangruber** [comment]
Hey Tod, thank you for reporting this. There has been a breaking change in the SDK between versions 0.7.0 and 0.8.0. Could you please use `Database -> Reset database` from the menu, or manually `rm -Rf ~/.p2pcommons` and try again?

**Comment by todrobbins** [comment]
That did it! Thanks!
