### ISSUE TITLE
Navigation menu text changes color unexpectedly

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#328]
## Description

The navigation menu text changes color while using Hypergraph.

## To Reproduce

1. Build from main
2. Go to profile
3. Click edit profile

## Expected behavior

Navigation menu text stays white.

## Actual behavior

Navigation menu text changes color (grey, red, green).

## Screenshots

![Screen Recording 2020-11-16 at 09 18 56 2020-11-16 09_21_27](https://user-images.githubusercontent.com/2946344/99228593-1f40b980-27ed-11eb-8592-2aac648d8def.gif)

## System

- OS (incl. version): macOS 10.15.7
- Hypergraph Desktop version: [`main@a34153ec0d137a79a42ad572437eecd64191c254`](https://github.com/hypergraph-xyz/desktop/commit/a34153ec0d137a79a42ad572437eecd64191c254)

## Additional context

This issue did not exist in the 0.8.0 release.

**Comment by chartgerink** [comment]
Seems like this issue first occurred in 260e74bf031444c088348268a0fdf6ab4a7719da

**Comment by chartgerink** [comment]
Seems like this is not fixed after all. :(

**Comment by juliangruber** [comment]
Yeah :/ I noticed this in https://github.com/hypergraph-xyz/desktop/pull/331#issuecomment-729604658 as well

**Comment by juliangruber** [comment]
I did like 30m of debugging and couldn't figure it out in that time

**Comment by chartgerink** [comment]
Thanks @juliangruber for spending time on this! It'll be interesting to figure this one out at some point. Will probably revisit this during the week..

**Comment by chartgerink** [comment]
Okay it really is a difference in the `package-lock.json` 🥝 Without changing any code, but just replacing the `package-lock.json` to the one from [this commit](https://github.com/hypergraph-xyz/desktop/blob/6287528985d7a40c6acb78370ab1cd31aa52689a/package-lock.json) fixes the issue again 🤷‍♀️ 

After I fixed it, I was no longer to reproduce the issue even. I tested some of the latest builds also on Windows, and the issue did seem fixed. Leaving this open for a bit longer to see whether we run into this again...

**Comment by chartgerink** [comment]
I haven't seen this since last comment, so closing this issue as it seems this has become stale. May be relevant to #332 in the future still...
