### ISSUE TITLE
Unexpected: remove parent

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#346]
This is probably on the roadmap, but it's unexpected that you can only clear all parents, not a single one

![image](https://user-images.githubusercontent.com/10247/106135537-5970f480-6168-11eb-862d-7576d10fcd42.png)

**Comment by chartgerink** [comment]
Fair point. There is supposed to be a hover X, although it only activates on the far right. Do you think it would be better to show that on the whole parent display?

With #352 we also get the text cursor back, and you can backspace delete individual ones. What do you think of this?
<img width="1552" alt="Screenshot 2021-02-05 at 10 49 14" src="https://user-images.githubusercontent.com/2946344/107017723-cb1bf480-679f-11eb-96ba-87f91e70aad3.png">

**Comment by juliangruber** [comment]
Ah cool, with a text cursor that makes sense for individual ones, I think I'd have to try then again.

**Comment by chartgerink** [comment]
Closed in #352.
