### ISSUE TITLE
Text in menu bar isn't styled correctly

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#37]
The text in the left menu bar isn't styled correctly. It seems that the `button` styling overrides it.
Running Windows 10 using this build: https://github.com/hypergraph-xyz/desktop/runs/498105561

![image](https://user-images.githubusercontent.com/59870484/76326388-d8f39c00-62e8-11ea-9b9c-2bc523cae1b0.png)

**Comment by juliangruber** [comment]
Can you describe how text styling differs?

**Comment by jameslibscie** [comment]
@juliangruber The spacing isn't applied, the weight seems different and I think it's not using the same font (but I'm not sure about that)

**Comment by juliangruber** [comment]
The current state of design does not allow for pixel perfect spacing, I will have to revisit this once this is consistent. Otherwise there's hacky manual adjustments all over the place.

**Comment by juliangruber** [comment]
<img width="328" alt="Screenshot 2020-03-10 at 16 20 57" src="https://user-images.githubusercontent.com/10247/76328115-2e30ad00-62eb-11ea-8f95-ee27ac929300.png">

Where is spacing different?

**Comment by juliangruber** [comment]
You were right however that it didn't use Roboto and our letter spacing, good catch!

**Comment by jameslibscie** [comment]
I see it's harder to notice on Mac since the OS default font is closer to Roboto (and much better looking) than the Windows default font.

Already checked the latest build and it looks great now :)
