### ISSUE TITLE
Prompted to enter profile name after update

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#385]
After updating to 0.10.0, it prompted me to update my keys (as expected), then afterwards showed the Vault and the profile name screen again (without my name prefilled), making me think I would have to create a new profile. Luckily, afterwards my old data was still there.

**Comment by chartgerink** [comment]
Thanks for reporting this! Was there any additional messages that came up or information you could share? I cannot reproduce this on my Windowse machine.

**Comment by juliangruber** [comment]
Unfortunately I don't have any extra information

**Comment by chartgerink** [comment]
Couldn't reproduce and have had no additional reports of this since the original post. Thanks for reporting the initial bug, and happy to reopen if it happens again.
