### ISSUE TITLE
Double clicking on a module row

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#386]
First, I found it unexpected that you needed to double click on a content row to open it, but then I remembered this was changed.

I did notice however that when you double click a content row it for a second selects the content type, before navigating.

![image](https://user-images.githubusercontent.com/10247/109435306-272e0d80-7a1a-11eb-9568-6b73e175a516.png)

**Comment by juliangruber** [comment]
I also think it's unexpected that you only double click on the content row, but nothing else in the app. It doesn't immediately make sense to me why that is. Eg, on Windows, you know you use double click on files/apps, but single click on anything else. The metaphor isn't as strong with Hypergraph.

I understand this feature is for being able to select text, but isn't it better to select text on the content detail screen, where the description isn't truncated?

**Comment by juliangruber** [comment]
I also find myself double-clicking on other stuff now, for example on the files of a content module, opening them twice by accident

**Comment by chartgerink** [comment]
Fair points. I tried to remove the selection when double clicking, but that happens to late in any case. I'll let @psobrakseaton weigh in for UX --- I am not necessarily opposed to switching to only selecting in the content screen and I'm happy to include this as a point in future tests.

**Comment by psobrakseaton** [comment]
These are really good points. I need a tiny bit to test this out and to check this out, 

> I understand this feature is for being able to select text, but isn't it better to select text on the content detail screen, where the description isn't truncated?

This to me is the most salient way to approach this, to only allow selection on the content page itself. I am definitely inclined to this direction.

**Comment by psobrakseaton** [comment]
Ok, I'm sorry it took so long for me to get around to this. I think this raises some questions about subtlety of interaction as far as Hypergraph is concerned.

I think what @juliangruber suggested about only selecting content in the details page not only follows the most common patterns, but also makes the most logical sense. Also, when double clicking on a file we should only open it once, and to open a second version there should be another deliberate action.

Additionally, I can see in the future, double clicking on an item in the content feed would open a separate window of the content details page (i.e. in a mail app like Julian mentioned earlier).

In summation, here is what I see should be changed at earliest convenience :
- [ ] Text selection should only work on the details screen.
- [ ] Single clicking or double clicking on files should only open one instance.

Also, what do you think about having the labels ("Main file") as selectable text? I think there could be an argument to not have them selectable on the details screen, but perhaps that is too much fine tuning...

**Comment by juliangruber** [comment]
> Also, what do you think about having the labels ("Main file") as selectable text? I think there could be an argument to not have them selectable on the details screen, but perhaps that is too much fine tuning...

I would test this and see if it's confusing without "Main file" in the clipboard or not
