### ISSUE TITLE
Can't open main file if markdown

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#387]
There's an inconsistency in the content screen: If the main file isn't a markdown file, you can open it by clicking on the file row. If it is a markdown file, you can't open it like this. I would expected main markdown files to also be listed in the files section.

**Comment by chartgerink** [comment]
Thanks for the comment 😊 

I noted this for our redesign of the content screen (forthcoming), and will close the issue in the meantime.
