### ISSUE TITLE
Error fetching content

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#388]
Not sure if this profile is still the current one, but I got this error looking at Chris' content:

![image](https://user-images.githubusercontent.com/10247/109436533-3dd76300-7a20-11eb-8353-d3465e35bf16.png)

The profile key is `hypergraph://2ae99d1441b7605a9775b2e1c7835d4ddaaafc9472b0a0fd6e9bf9607dd210b5`.

**Comment by juliangruber** [comment]
The module is this:

![image](https://user-images.githubusercontent.com/10247/109436556-59db0480-7a20-11eb-8cb0-5519530b8809.png)

**Comment by chartgerink** [comment]
Interesting, this didn't come up during testing before the release. I was able to reproduce it on a 100% clean install, but it went away after I rebooted the application (and reset database). It seems like this is a connect to swarm issue, which has been popping up somewhat inconsistently.

It definitely shouldn't happen, so leaving this issue open for now.

**Comment by todrobbins** [comment]
I can confirm that I had the same error upon launching/interacting with content with v0.10.0 on macOS:

<img width="1552" alt="Screen Shot 2021-02-28 at 10 04 40 PM" src="https://user-images.githubusercontent.com/158590/109570199-e8926480-7aa6-11eb-9830-fff1c2001954.png">

But the issue resolved after reopening:

![Screen Shot 2021-03-01 at 3 58 39 PM](https://user-images.githubusercontent.com/158590/109570277-0364d900-7aa7-11eb-8b3f-6e1f35afec4b.png)

**Comment by chartgerink** [comment]
Seems like this is may be a swarm connection issue, so pinging @dpaez for any potential insights he might have!
