### ISSUE TITLE
Welcome screen opens if profile is created through CLI

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#40]
If I create a profile using the latest version of the CLI, Hypergraph Desktop still opens the welcome modals and prompts me to create a profile. The welcome screen should not show if I already have a profile.

**Comment by juliangruber** [comment]
I can't reproduce this, please use latest master, not the release of hypergraph

**Comment by jameslibscie** [comment]
Was indeed caused by SDK compatibility issues - now solved!
