### ISSUE TITLE
General error handling

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#42]
**User story**
As a Hypergraph user
I want to know when something goes wrong in the program
so that I know what's going on and can alert the developers of issues

**Acceptance criteria**
- [ ] Any otherwise unhandled error generates an alert (or similar) that provides the user with a description of that error (may be a stack trace or other error that is not user friendly)
- [ ] The alert suggests that they send a screenshot to `feedback@libscie.org` along with a description of what they were doing at the time
- [x] `feedback@libscie.org` needs to be created and forwards to `jameslibscie@gmail.com` (this has already been requested from @chartgerink)
- [ ] The alert can be closed and the user can continue using Hypergraph afterwards

**Comment by chartgerink** [comment]
I created the `feedback@libscie.org` collaborative inbox. Please ping me if anybody needs to be added. :)
