### ISSUE TITLE
Input validation for create profile and add content

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#43]
**User story**
As a Hypergraph user
I want guidance on inputting valid data
so that I know what I can and can't input

**Workflow**

- [x] Design
- [x] Code

**Acceptance criteria**
- Profile and content titles are validated for the maximum character length of 300
- Validation occurs as the user types
- If an invalid title is entered, the user is immediately provided with an error message directly above or below the input field: "Title may not be longer than 300 characters" (or similar). Suggestion: This text is displayed in red and the input field is highlighted red
- Once the title becomes valid, the error and all error highlighting / indications disappear
- The user may not continue (submit the form) while there is an error, but may cancel a form (applies to "add content" only, as "create profile" cannot be canceled)

**Comment by juliangruber** [comment]
@psobrakseaton is this ready to be implemented?

**Comment by juliangruber** [comment]
@jameslibscie this has landed in master, can you check it please?

**Comment by jameslibscie** [comment]
Very nice!
