### ISSUE TITLE
Delete published module doesn't work

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#45]
Delete content doesn't work properly on published modules. It deletes the module at first, but then the profile no longer shows any content (including published content that hasn't been deleted). Later the deleted module reappears on the workspace and the profile.

Reproduction:
- Create two modules
- Publish both of them
- Delete one of them
- Visit profile
- Wait a while
- Visit workspace & profile again

**Comment by jameslibscie** [comment]
If this doesn't work because of an SDK issue, then perhaps it is better to hide the delete button for published modules, so you have to unpublish and then delete. That might make more sense anyway.

**Comment by chartgerink** [comment]
I also noted some odd behavior that it got deleted from Hypergraph but not from `~/.p2pcommons`? Maybe not related but thought I'd mention.

**Comment by jameslibscie** [comment]
> I also noted some odd behavior that it got deleted from Hypergraph but not from `~/.p2pcommons`? Maybe not related but thought I'd mention.

Diego has just made an option for this on the `delete` function for the SDK, so we can also trash the files from the `.p2pcommons` folder. I suggest that we implement this on Desktop once it's available.

**Comment by jameslibscie** [comment]
I have folders for specific versions of dat archives in my `p2pcommons` folder, like:
```
89510dd457da8729582557d062c3a8cc808ddc202d75ede159f282318f8d899e
89510dd457da8729582557d062c3a8cc808ddc202d75ede159f282318f8d899e+6
dd4807399788a0f5a18f1214c9c46cb2e7d9b5c7e64b60820392c56adedcfc84
dd4807399788a0f5a18f1214c9c46cb2e7d9b5c7e64b60820392c56adedcfc84+4
```

I think this is related to this bug, as these are modules that I've deleted while they were published.

**Comment by juliangruber** [comment]
I can reproduce this, thanks for posting the steps to reproduce!

@dpaez this does look like an SDK issue, could you take a look at it?

**Comment by juliangruber** [comment]
The issue was that `p2p.delete()` doesn't remove the module from the profile's `.contents[]`, so I had to add a `p2p.unpublish()` before the `p2p.delete()`. @jameslibscie what do you think about that?

**Comment by dpaez** [comment]
@juliangruber and all, I totally miss this last week. I think the problem could be more related to not deleting co-related metadata like what @juliangruber mentions. I'm thinking that we can add an `unpublish` step to the delete method call (this will result on an extra `unpublish` call every time we `delete` something).

**Comment by juliangruber** [comment]
That option sounds good! Maybe we could even enable it by default
