### ISSUE TITLE
Formulate clickthrough test plan

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#5]
As a Hypergraph developer
I want to learn as much as possible about the usability of what we're making
so that we can iterate quickly and put out a kick-ass product asap

What we want to learn:
- How well do they understand the concept of the application? What does it take for the concept to come across? (as-you-go, decentralisation)
- What relevance do they see to their work?
- Are they able to use the (mocked up) software as we intended?
- What do they think of the design aesthetically? What are their associations?

To do:
- [x] What do we want to learn?
- [x] Test script for clickthrough with users
- [x] Internal clickthrough for early feedback
- [ ] Update issue with test script

**Comment by jameslibscie** [comment]
@psobrakseaton @nehamoopen On what day(s) could we have a call about this? I'm available Tuesday-Friday.

**Comment by nehamoopen** [comment]
@psobrakseaton @jameslibscie I'm available Thursday 12:45 - 14:45 & Friday after 15:00

**Comment by jameslibscie** [comment]
First of all, thanks for helping us to test Hypergraph. What this session will entail is that I will show you a mock-up of the first version of our software that you can click through. It isn't at all functional, although it will respond to clicking in various places and contains some example content. I'll ask some questions about your experience while clicking through to see whether everything is coming across as intended. <Note taker> will be taking notes during the session and might ask a question or two here or there. Later I will ask you to share your screen as well. Is that OK? By the way, is it OK if we record the audio and video for this session? This material will not be shared outside the organisation and will only be kept as long as necessary to write up a report.

Don't forget we're not testing you, so there are no wrong or right answers and all feedback is helpful to us. Also, there's no need to be nice to please us, critical feedback helps us much more.

…

So, before we show you the first screen, I'd like to ask you: What do you already know about Hypergraph and Liberate Science?

Have you heard of the term *as-you-go* publishing? If so, how much do you know about it?

…

<Prompt to share screen>

…

I'm going to send you a link to the clickthrough in a moment. Imagine you've just installed Hypergraph and are ready to open it for the first time. When you open the link, I want to hear the first words that pop into your head.

…

Now, please start to use this software as though you're looking around for the first time and while doing so, tell us as much as you can about what you see. Let us know if something is different than what you expect and ask as many questions as you need to understand what's going on.

…

<Questions we can ask along the way if they don't naturally answer these themselves OR afterwards if that seems more natural. We can direct them to the correct page first if necessary>

How does this text make you feel?

How would you describe as-you-go publishing to one of your colleagues?

Do you usually read these welcome texts when using new software or skip them?

Have you heard of the "Vault" and do you know what it is for?

<Profile first visit> What are your associations with this visual style? How does it make you feel? What do you and don't you like about it?

If you wanted to read the full text for the theory named "The meaninglessness of excellence", how would you achieve that in this software?

<Theory> If you wanted to update one of the files for "The meaninglessness of excellence", how would you do that?

<Theory> What do you think "open folder" would do?

<Theory> What do you think "unpublish" would do?

<Theory> What other things do you think you can click on and what do you expect those to do?

<Home> What did you expect to be here? And what do you see here now?

<Home> What do you think "not yet published…" means?

<Abstract> What do you think "publish" would do?

How would you go about adding new in-progress content to Hypergraph? <more concrete>

And how would you then add that to your profile?

<Add content> What would you select here for "Follows from…" if you were working on a completely new project? And if you were working on a statistical analysis? How about a data set? Or a conclusion?

<Add content> Do you know about Creative Commons licensing? Do you know approximately what publishing with a public domain license would entail? Would you feel comfortable publishing your work under a public domain license? What would your concerns be?

…

I think we've covered the basics now, so I'd consider you introduced to the software. Now imagine yourself using Hypergraph to manage your next research project from start to finish. Perhaps you already have one in mind. Could you guide me through the general steps you'd take in Hypergraph to get your research added into Hypergraph and published?

What do you like and dislike about this process?

What is your opinion so far on *as-you-go* publishing?

What is your opinion so far on the software in general?

And what about the look and feel of the application?

What features are you missing now that are essential to you?

…

That’s all! Thank you so much for your time, it's extremely valuable to us. Would you like me to send you a summary of these sessions so you can hear about what we've learned from you and other testers as well?
