### ISSUE TITLE
refactor using design units

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#53]
Most of designs are built on top of a 8px/16px/32px/64px grid. Instead of hard coding these values, create a unit library that scales to the desired dimensions.

Eg, instead of

```js
{ width: '64px' }
```

use

```js
{ width: unit(8) }
```

@jameslibscie there's currently not an appropriate label for refactorings like this

**Comment by jameslibscie** [comment]
@juliangruber I've added a `tech` label for all technical housekeeping, such as refactors, CI improvements, etc. Does that work for you?

**Comment by juliangruber** [comment]
Yes lovely :)

**Comment by jameslibscie** [comment]
> Yes lovely :)

Cool! I've added it and a `cosmetic` label to repos where applicable
