### ISSUE TITLE
Back arrow inconsistent

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#55]
## Description
In some cases the back arrow that is shown on a module page takes you back to the wrong page.

## To Reproduce

1. Create a module
1. Publish module
1. Go to profile
1. Click on module -> you are now on the module's profile content page
1. Unpublish that module -> you are now on the module's workspace content page
1. Click on the back arrow

## Expected behavior
You are now on the workspace

## Actual behavior
You are now on the module's profile content page, although it is unpublished

## Screenshots

Published module:

<img width="932" alt="Screenshot 2020-03-31 at 10 16 50" src="https://user-images.githubusercontent.com/10247/78003348-ca713100-7338-11ea-8ed1-90695fa4f387.png">

Then unpublished module:

<img width="932" alt="Screenshot 2020-03-31 at 10 16 57" src="https://user-images.githubusercontent.com/10247/78003356-cc3af480-7338-11ea-9585-cb18a049ee51.png">

Click on back arrow:

<img width="932" alt="Screenshot 2020-03-31 at 10 17 02" src="https://user-images.githubusercontent.com/10247/78003364-cf35e500-7338-11ea-8ab1-2267d2ad021b.png">

## Desktop

- OS: macOS
- Version: https://github.com/hypergraph-xyz/desktop/pull/51

## Additional context

This bug also prevents us from removing published modules from the workspace page, as it would occur twice as often then

**Comment by jameslibscie** [comment]
Nice catch, but I would personally expect to go back to the profile, since that's the page I came from. I would expect to go to the workspace if it were an 'Up' button, rather than 'Back'.

**Comment by juliangruber** [comment]
> Nice catch, but I would personally expect to go back to the profile, since that's the page I came from.

Oooh ok let me try that

**Comment by juliangruber** [comment]
this works well for now!
