### ISSUE TITLE
Shorten file names

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#56]
**User story**
As a Hypergraph user
I want file names to be shortened
so that I can see the file extensions

**Acceptance criteria**
- The file names no longer run up to or over icons (or the edge of the field) when:
- [x] adding content
- [x] viewing content
- [ ] selecting the main file

**Comment by juliangruber** [comment]
> The file extension remains visible at all times (assuming the window size isn't ridiculously small)

This was intended as an iteration and doesn't need to be implemented right away.

**Comment by juliangruber** [comment]
> I want file names to be shortened
> so that I can see the file extensions

I don't think you want file names to be shortened in order to see file extensions. When they are shortened, you want to keep file extensions. You want them to be shortened so they don't break the design.

**Comment by juliangruber** [comment]
The basic ellipsis strategy has been implemented.

**Comment by jameslibscie** [comment]
Good points. To me this issue has two elements, one of which could indeed be deferred (the file extension thing). The design aspect is purely a cosmetic thing (which doesn't need a user story imo) and the file extension aspect is a potential usability thing (which is why I wrote the story from that perspective).

I'm glad we're going to be talking about process changes very soon, because this often gets messy ^^ I notice I have a tendency not to seek clarification because it's such a small issue, even though I do actually need it to write up the issue properly.

I'll check out the work and then close the issue if it looks good :)

**Comment by juliangruber** [comment]
> I notice I have a tendency not to seek clarification because it's such a small issue, even though I do actually need it to write up the issue properly.

Sometimes the only way to be more efficient is to slow down.

**Comment by jameslibscie** [comment]
Technically not part of the spec, but I've noticed long filenames also run over on the 'Main file' selector. Could you shorten it there as well?
