### ISSUE TITLE
App & setup icon pixelated on Windows

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#65]
## Description

The app icon displays pixelated in Windows in the following places:
- Icon of `Hypergraph-Setup.exe` file
- Icon within the setup process
- Desktop shortcut to installed app
- Icon on taskbar
etc.

## To Reproduce

1. Download installer on Windows -> logo is pixelated
2. Run installer -> logo is pixelated
3. Shortcut on desktop -> logo is pixelated
etc.

## Expected behavior

The logo should show smoothly. This happens correctly on Mac and in the app itself.

## Screenshots

This shows the desktop icon and the in-app logo next to each other.
![2020-04-09 pixelated logo](https://user-images.githubusercontent.com/59870484/78900080-9dc6c300-7a76-11ea-8341-5c2cc58c4b1a.png)

## Desktop

- OS: Windows 10
- Version: v0.1.0

**Comment by juliangruber** [comment]
once you have an `ico`, you can post it here or open a pull request to add it to `build/icon.ico`.

**Comment by jameslibscie** [comment]
![image](https://user-images.githubusercontent.com/59870484/79555576-1f82a600-80a0-11ea-967c-4e9121aa05c6.png)

**Comment by juliangruber** [comment]
ico: https://libscie.slack.com/files/UQU8PLD1D/F012SA6UF60/hypergraph-icon.ico
