### ISSUE TITLE
Update content module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#69]
**User story**
As a content creator
I want to update the title and description of my content
so that I can correct mistakes and make adjustments as work progresses

**Acceptance criteria**
- [ ] The content title is editable
- [ ] The description is editable
- [ ] It is possible to cancel in-progress changes
- [ ] It must not be possible for users to enter a content title that does not adhere to the specs (at the version currently implemented by the SDK version used)
- [ ] If the content does not have a description, the user is prompted to add one (for example, the text "Add a description..." is displayed greyed out with some kind of visual cue to indicate editability)

**Comment by juliangruber** [comment]
Where to put the "Edit content" button? Probably next to "Open folder" or "Export .zip".

<img width="1158" alt="Screenshot 2020-05-27 at 09 58 16" src="https://user-images.githubusercontent.com/10247/82993651-343c4d00-a001-11ea-8f83-89e60a227841.png">

**Comment by juliangruber** [comment]
- [ ] the content type is editable

**Comment by juliangruber** [comment]
Blocked by https://github.com/p2pcommons/sdk-js/issues/195

**Comment by juliangruber** [comment]
Blocked by https://github.com/p2pcommons/sdk-js/pull/216

**Comment by juliangruber** [comment]
To change the parent, set it to `null` first. Prevent the error by only having versioned parents.

**Comment by juliangruber** [comment]
For now we will only implement updating drafts, as there are more complications to updating registered content
