### ISSUE TITLE
Multi-line descriptions show as single-line

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#70]
## Description

If a description contains multiple lines (with newline characters), it gets displayed on a single line.

## To Reproduce

1. Go to "Add content"
2. Add a multi-line description, like:
```
Line 1.
Line 2.
```
3. Save content
4. View content / go to content list

## Expected behavior

The text "Line 1" and "Line 2" are shown on separate lines.

## Actual behavior

The text "Line 1" and "Line 2" is shown on one line.

## Screenshots

![image](https://user-images.githubusercontent.com/59870484/80498937-a1aa7e80-896c-11ea-9fee-f517ff97d833.png)

## Desktop

- OS: Windows
- Version: 0.1.0

**Comment by juliangruber** [comment]
Note to self: replace `\n` with `<p>..</p>`
