### ISSUE TITLE
Error message when internet connection is blocked

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#71]
## Description

If the user blocks Hypergraph from connecting to the internet (for example with a firewall), an error is displayed upon most actions (create profile, add content). The loading animation then keeps running indefinitely. Closing and re-opening application works, and the action is (mostly) completed successfully. When adding content, the files were missing.

## To Reproduce

Haven't attempted reproduction yet. Block Hypergraph with a firewall before opening it or try also using Hypergraph without an internet connection at all.

## Screenshots

![vlcsnap-2020-04-24-17h14m34s452](https://user-images.githubusercontent.com/59870484/80503630-6e6aee00-8972-11ea-8124-b69e0ba49228.png)

## Desktop

- OS: Windows
- Version: 0.1.0

**Comment by juliangruber** [comment]
I think this means it's unable to reach the DHT. This issue will belong into the "debugging network issues" category, which means we also need to surface in the UI what the state of the network is

**Comment by jameslibscie** [comment]
Seems to be fixed by #168
