### ISSUE TITLE
Opening multiple instances

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#80]
On both Windows and Mac, Hypergraph displays an error if you open multiple instances. This is correct, as only one Hypergraph instance can run, but not very user friendly. Would it be possible to prevent further instances from opening altogether? And if not, could we make the error message more user-friendly?

**Comment by juliangruber** [comment]
I guess we can just bring up and focus the already running instance instead :+1:

**Comment by jameslibscie** [comment]
Perfect! In the test in question, the Hypergraph window somehow opened in the background (Mac), so the participant didn't know that Hypergraph was already open. Bringing up the running instance would be ideal :)

**Comment by juliangruber** [comment]
I can't reproduce this on mac, when you try to open it again it brings the existing app to the front and doesn't show an error. Can you provide the error message, a screen cast or screen shot?

**Comment by juliangruber** [comment]
It's also very unlikely this was a problem in a prior version of the app, as the logic for handling multiple instances was part of the first commit.

**Comment by juliangruber** [comment]
I can however reproduce this on Windows, it shows the db lock error message.

**Comment by jameslibscie** [comment]
![01-unidentified developer](https://user-images.githubusercontent.com/59870484/82907376-d529fa00-9f66-11ea-905b-20456261cac4.jpg)
![02-IO error lock](https://user-images.githubusercontent.com/59870484/82907383-d6f3bd80-9f66-11ea-8393-8aec1624b17b.jpg)
![03-multiple instances](https://user-images.githubusercontent.com/59870484/82907388-d8bd8100-9f66-11ea-92ae-4135edd18616.jpg)

After clicking open on the first dialog, Hypergraph opened in the background. Clicking the Hypergraph icon in the dock opened new instances.

Some weird edge conditions that may be relevant:
- The .dmg was still open
- The application was opened using ctrl (or cmd) + click on the icon to pop up the first window, rather than going through system preferences
- This was the second attempt to open the application, as the first time it was blocked because of unsigned code
