### ISSUE TITLE
dynamic page titles

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#83]
Using react-router we can change the page title as the user navigates. This will make the navigation data in Chatra more useful:

![Screenshot 2020-05-25 at 12 13 17](https://user-images.githubusercontent.com/10247/82803613-1fd14680-9e81-11ea-8ce3-414d4d5de099.png)

**Comment by jameslibscie** [comment]
Would this also affect the window title?

**Comment by juliangruber** [comment]
Good question, it should not.

**Comment by jameslibscie** [comment]
Agreed :)

**Comment by juliangruber** [comment]
Impossible without changing the window title that is visible to the user too unfortunately
